// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common_subject/v1/common_subject.proto

package commonsubjectv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCommonSubjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translations  map[string]string      `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommonSubjectRequest) Reset() {
	*x = CreateCommonSubjectRequest{}
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommonSubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommonSubjectRequest) ProtoMessage() {}

func (x *CreateCommonSubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommonSubjectRequest.ProtoReflect.Descriptor instead.
func (*CreateCommonSubjectRequest) Descriptor() ([]byte, []int) {
	return file_common_subject_v1_common_subject_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCommonSubjectRequest) GetTranslations() map[string]string {
	if x != nil {
		return x.Translations
	}
	return nil
}

type UpdateCommonSubjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Translations  map[string]string      `protobuf:"bytes,2,rep,name=translations,proto3" json:"translations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommonSubjectRequest) Reset() {
	*x = UpdateCommonSubjectRequest{}
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommonSubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommonSubjectRequest) ProtoMessage() {}

func (x *UpdateCommonSubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommonSubjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommonSubjectRequest) Descriptor() ([]byte, []int) {
	return file_common_subject_v1_common_subject_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCommonSubjectRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCommonSubjectRequest) GetTranslations() map[string]string {
	if x != nil {
		return x.Translations
	}
	return nil
}

type GetCommonSubjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommonSubjectRequest) Reset() {
	*x = GetCommonSubjectRequest{}
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommonSubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommonSubjectRequest) ProtoMessage() {}

func (x *GetCommonSubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommonSubjectRequest.ProtoReflect.Descriptor instead.
func (*GetCommonSubjectRequest) Descriptor() ([]byte, []int) {
	return file_common_subject_v1_common_subject_proto_rawDescGZIP(), []int{2}
}

func (x *GetCommonSubjectRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllCommonSubjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int32                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCommonSubjectsRequest) Reset() {
	*x = GetAllCommonSubjectsRequest{}
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCommonSubjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCommonSubjectsRequest) ProtoMessage() {}

func (x *GetAllCommonSubjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCommonSubjectsRequest.ProtoReflect.Descriptor instead.
func (*GetAllCommonSubjectsRequest) Descriptor() ([]byte, []int) {
	return file_common_subject_v1_common_subject_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllCommonSubjectsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetAllCommonSubjectsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type DeleteCommonSubjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommonSubjectRequest) Reset() {
	*x = DeleteCommonSubjectRequest{}
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommonSubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommonSubjectRequest) ProtoMessage() {}

func (x *DeleteCommonSubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommonSubjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommonSubjectRequest) Descriptor() ([]byte, []int) {
	return file_common_subject_v1_common_subject_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommonSubjectRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CommonSubjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonSubjectResponse) Reset() {
	*x = CommonSubjectResponse{}
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonSubjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSubjectResponse) ProtoMessage() {}

func (x *CommonSubjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSubjectResponse.ProtoReflect.Descriptor instead.
func (*CommonSubjectResponse) Descriptor() ([]byte, []int) {
	return file_common_subject_v1_common_subject_proto_rawDescGZIP(), []int{5}
}

func (x *CommonSubjectResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommonSubjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommonSubjectResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CommonSubjectResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetAllCommonSubjectsResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	CommonSubjects []*CommonSubjectResponse `protobuf:"bytes,1,rep,name=common_subjects,json=commonSubjects,proto3" json:"common_subjects,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAllCommonSubjectsResponse) Reset() {
	*x = GetAllCommonSubjectsResponse{}
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCommonSubjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCommonSubjectsResponse) ProtoMessage() {}

func (x *GetAllCommonSubjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCommonSubjectsResponse.ProtoReflect.Descriptor instead.
func (*GetAllCommonSubjectsResponse) Descriptor() ([]byte, []int) {
	return file_common_subject_v1_common_subject_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllCommonSubjectsResponse) GetCommonSubjects() []*CommonSubjectResponse {
	if x != nil {
		return x.CommonSubjects
	}
	return nil
}

type DeleteCommonSubjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommonSubjectResponse) Reset() {
	*x = DeleteCommonSubjectResponse{}
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommonSubjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommonSubjectResponse) ProtoMessage() {}

func (x *DeleteCommonSubjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_subject_v1_common_subject_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommonSubjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommonSubjectResponse) Descriptor() ([]byte, []int) {
	return file_common_subject_v1_common_subject_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCommonSubjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_subject_v1_common_subject_proto protoreflect.FileDescriptor

const file_common_subject_v1_common_subject_proto_rawDesc = "" +
	"\n" +
	"&common_subject/v1/common_subject.proto\x12\x11common_subject.v1\"\xc2\x01\n" +
	"\x1aCreateCommonSubjectRequest\x12c\n" +
	"\ftranslations\x18\x01 \x03(\v2?.common_subject.v1.CreateCommonSubjectRequest.TranslationsEntryR\ftranslations\x1a?\n" +
	"\x11TranslationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd2\x01\n" +
	"\x1aUpdateCommonSubjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12c\n" +
	"\ftranslations\x18\x02 \x03(\v2?.common_subject.v1.UpdateCommonSubjectRequest.TranslationsEntryR\ftranslations\x1a?\n" +
	"\x11TranslationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x17GetCommonSubjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"j\n" +
	"\x1bGetAllCommonSubjectsRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\",\n" +
	"\x1aDeleteCommonSubjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"y\n" +
	"\x15CommonSubjectResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"q\n" +
	"\x1cGetAllCommonSubjectsResponse\x12Q\n" +
	"\x0fcommon_subjects\x18\x01 \x03(\v2(.common_subject.v1.CommonSubjectResponseR\x0ecommonSubjects\"7\n" +
	"\x1bDeleteCommonSubjectResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xcf\x04\n" +
	"\x14CommonSubjectService\x12n\n" +
	"\x13CreateCommonSubject\x12-.common_subject.v1.CreateCommonSubjectRequest\x1a(.common_subject.v1.CommonSubjectResponse\x12h\n" +
	"\x10GetCommonSubject\x12*.common_subject.v1.GetCommonSubjectRequest\x1a(.common_subject.v1.CommonSubjectResponse\x12w\n" +
	"\x14GetAllCommonSubjects\x12..common_subject.v1.GetAllCommonSubjectsRequest\x1a/.common_subject.v1.GetAllCommonSubjectsResponse\x12n\n" +
	"\x13UpdateCommonSubject\x12-.common_subject.v1.UpdateCommonSubjectRequest\x1a(.common_subject.v1.CommonSubjectResponse\x12t\n" +
	"\x13DeleteCommonSubject\x12-.common_subject.v1.DeleteCommonSubjectRequest\x1a..common_subject.v1.DeleteCommonSubjectResponseBUZSgithub.com/Talan-Application/proto-generation/gen/common_subject/v1;commonsubjectv1b\x06proto3"

var (
	file_common_subject_v1_common_subject_proto_rawDescOnce sync.Once
	file_common_subject_v1_common_subject_proto_rawDescData []byte
)

func file_common_subject_v1_common_subject_proto_rawDescGZIP() []byte {
	file_common_subject_v1_common_subject_proto_rawDescOnce.Do(func() {
		file_common_subject_v1_common_subject_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_subject_v1_common_subject_proto_rawDesc), len(file_common_subject_v1_common_subject_proto_rawDesc)))
	})
	return file_common_subject_v1_common_subject_proto_rawDescData
}

var file_common_subject_v1_common_subject_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_common_subject_v1_common_subject_proto_goTypes = []any{
	(*CreateCommonSubjectRequest)(nil),   // 0: common_subject.v1.CreateCommonSubjectRequest
	(*UpdateCommonSubjectRequest)(nil),   // 1: common_subject.v1.UpdateCommonSubjectRequest
	(*GetCommonSubjectRequest)(nil),      // 2: common_subject.v1.GetCommonSubjectRequest
	(*GetAllCommonSubjectsRequest)(nil),  // 3: common_subject.v1.GetAllCommonSubjectsRequest
	(*DeleteCommonSubjectRequest)(nil),   // 4: common_subject.v1.DeleteCommonSubjectRequest
	(*CommonSubjectResponse)(nil),        // 5: common_subject.v1.CommonSubjectResponse
	(*GetAllCommonSubjectsResponse)(nil), // 6: common_subject.v1.GetAllCommonSubjectsResponse
	(*DeleteCommonSubjectResponse)(nil),  // 7: common_subject.v1.DeleteCommonSubjectResponse
	nil,                                  // 8: common_subject.v1.CreateCommonSubjectRequest.TranslationsEntry
	nil,                                  // 9: common_subject.v1.UpdateCommonSubjectRequest.TranslationsEntry
}
var file_common_subject_v1_common_subject_proto_depIdxs = []int32{
	8, // 0: common_subject.v1.CreateCommonSubjectRequest.translations:type_name -> common_subject.v1.CreateCommonSubjectRequest.TranslationsEntry
	9, // 1: common_subject.v1.UpdateCommonSubjectRequest.translations:type_name -> common_subject.v1.UpdateCommonSubjectRequest.TranslationsEntry
	5, // 2: common_subject.v1.GetAllCommonSubjectsResponse.common_subjects:type_name -> common_subject.v1.CommonSubjectResponse
	0, // 3: common_subject.v1.CommonSubjectService.CreateCommonSubject:input_type -> common_subject.v1.CreateCommonSubjectRequest
	2, // 4: common_subject.v1.CommonSubjectService.GetCommonSubject:input_type -> common_subject.v1.GetCommonSubjectRequest
	3, // 5: common_subject.v1.CommonSubjectService.GetAllCommonSubjects:input_type -> common_subject.v1.GetAllCommonSubjectsRequest
	1, // 6: common_subject.v1.CommonSubjectService.UpdateCommonSubject:input_type -> common_subject.v1.UpdateCommonSubjectRequest
	4, // 7: common_subject.v1.CommonSubjectService.DeleteCommonSubject:input_type -> common_subject.v1.DeleteCommonSubjectRequest
	5, // 8: common_subject.v1.CommonSubjectService.CreateCommonSubject:output_type -> common_subject.v1.CommonSubjectResponse
	5, // 9: common_subject.v1.CommonSubjectService.GetCommonSubject:output_type -> common_subject.v1.CommonSubjectResponse
	6, // 10: common_subject.v1.CommonSubjectService.GetAllCommonSubjects:output_type -> common_subject.v1.GetAllCommonSubjectsResponse
	5, // 11: common_subject.v1.CommonSubjectService.UpdateCommonSubject:output_type -> common_subject.v1.CommonSubjectResponse
	7, // 12: common_subject.v1.CommonSubjectService.DeleteCommonSubject:output_type -> common_subject.v1.DeleteCommonSubjectResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_subject_v1_common_subject_proto_init() }
func file_common_subject_v1_common_subject_proto_init() {
	if File_common_subject_v1_common_subject_proto != nil {
		return
	}
	file_common_subject_v1_common_subject_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_subject_v1_common_subject_proto_rawDesc), len(file_common_subject_v1_common_subject_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_subject_v1_common_subject_proto_goTypes,
		DependencyIndexes: file_common_subject_v1_common_subject_proto_depIdxs,
		MessageInfos:      file_common_subject_v1_common_subject_proto_msgTypes,
	}.Build()
	File_common_subject_v1_common_subject_proto = out.File
	file_common_subject_v1_common_subject_proto_goTypes = nil
	file_common_subject_v1_common_subject_proto_depIdxs = nil
}
