// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: common_subject/v1/common_subject.proto

package commonsubjectv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommonSubjectService_CreateCommonSubject_FullMethodName  = "/common_subject.v1.CommonSubjectService/CreateCommonSubject"
	CommonSubjectService_GetCommonSubject_FullMethodName     = "/common_subject.v1.CommonSubjectService/GetCommonSubject"
	CommonSubjectService_GetAllCommonSubjects_FullMethodName = "/common_subject.v1.CommonSubjectService/GetAllCommonSubjects"
	CommonSubjectService_UpdateCommonSubject_FullMethodName  = "/common_subject.v1.CommonSubjectService/UpdateCommonSubject"
	CommonSubjectService_DeleteCommonSubject_FullMethodName  = "/common_subject.v1.CommonSubjectService/DeleteCommonSubject"
)

// CommonSubjectServiceClient is the client API for CommonSubjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommonSubjectServiceClient interface {
	CreateCommonSubject(ctx context.Context, in *CreateCommonSubjectRequest, opts ...grpc.CallOption) (*CommonSubjectResponse, error)
	GetCommonSubject(ctx context.Context, in *GetCommonSubjectRequest, opts ...grpc.CallOption) (*CommonSubjectResponse, error)
	GetAllCommonSubjects(ctx context.Context, in *GetAllCommonSubjectsRequest, opts ...grpc.CallOption) (*GetAllCommonSubjectsResponse, error)
	UpdateCommonSubject(ctx context.Context, in *UpdateCommonSubjectRequest, opts ...grpc.CallOption) (*CommonSubjectResponse, error)
	DeleteCommonSubject(ctx context.Context, in *DeleteCommonSubjectRequest, opts ...grpc.CallOption) (*DeleteCommonSubjectResponse, error)
}

type commonSubjectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonSubjectServiceClient(cc grpc.ClientConnInterface) CommonSubjectServiceClient {
	return &commonSubjectServiceClient{cc}
}

func (c *commonSubjectServiceClient) CreateCommonSubject(ctx context.Context, in *CreateCommonSubjectRequest, opts ...grpc.CallOption) (*CommonSubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonSubjectResponse)
	err := c.cc.Invoke(ctx, CommonSubjectService_CreateCommonSubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonSubjectServiceClient) GetCommonSubject(ctx context.Context, in *GetCommonSubjectRequest, opts ...grpc.CallOption) (*CommonSubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonSubjectResponse)
	err := c.cc.Invoke(ctx, CommonSubjectService_GetCommonSubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonSubjectServiceClient) GetAllCommonSubjects(ctx context.Context, in *GetAllCommonSubjectsRequest, opts ...grpc.CallOption) (*GetAllCommonSubjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllCommonSubjectsResponse)
	err := c.cc.Invoke(ctx, CommonSubjectService_GetAllCommonSubjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonSubjectServiceClient) UpdateCommonSubject(ctx context.Context, in *UpdateCommonSubjectRequest, opts ...grpc.CallOption) (*CommonSubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonSubjectResponse)
	err := c.cc.Invoke(ctx, CommonSubjectService_UpdateCommonSubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonSubjectServiceClient) DeleteCommonSubject(ctx context.Context, in *DeleteCommonSubjectRequest, opts ...grpc.CallOption) (*DeleteCommonSubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommonSubjectResponse)
	err := c.cc.Invoke(ctx, CommonSubjectService_DeleteCommonSubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonSubjectServiceServer is the server API for CommonSubjectService service.
// All implementations must embed UnimplementedCommonSubjectServiceServer
// for forward compatibility.
type CommonSubjectServiceServer interface {
	CreateCommonSubject(context.Context, *CreateCommonSubjectRequest) (*CommonSubjectResponse, error)
	GetCommonSubject(context.Context, *GetCommonSubjectRequest) (*CommonSubjectResponse, error)
	GetAllCommonSubjects(context.Context, *GetAllCommonSubjectsRequest) (*GetAllCommonSubjectsResponse, error)
	UpdateCommonSubject(context.Context, *UpdateCommonSubjectRequest) (*CommonSubjectResponse, error)
	DeleteCommonSubject(context.Context, *DeleteCommonSubjectRequest) (*DeleteCommonSubjectResponse, error)
	mustEmbedUnimplementedCommonSubjectServiceServer()
}

// UnimplementedCommonSubjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommonSubjectServiceServer struct{}

func (UnimplementedCommonSubjectServiceServer) CreateCommonSubject(context.Context, *CreateCommonSubjectRequest) (*CommonSubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCommonSubject not implemented")
}
func (UnimplementedCommonSubjectServiceServer) GetCommonSubject(context.Context, *GetCommonSubjectRequest) (*CommonSubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommonSubject not implemented")
}
func (UnimplementedCommonSubjectServiceServer) GetAllCommonSubjects(context.Context, *GetAllCommonSubjectsRequest) (*GetAllCommonSubjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllCommonSubjects not implemented")
}
func (UnimplementedCommonSubjectServiceServer) UpdateCommonSubject(context.Context, *UpdateCommonSubjectRequest) (*CommonSubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCommonSubject not implemented")
}
func (UnimplementedCommonSubjectServiceServer) DeleteCommonSubject(context.Context, *DeleteCommonSubjectRequest) (*DeleteCommonSubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCommonSubject not implemented")
}
func (UnimplementedCommonSubjectServiceServer) mustEmbedUnimplementedCommonSubjectServiceServer() {}
func (UnimplementedCommonSubjectServiceServer) testEmbeddedByValue()                              {}

// UnsafeCommonSubjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommonSubjectServiceServer will
// result in compilation errors.
type UnsafeCommonSubjectServiceServer interface {
	mustEmbedUnimplementedCommonSubjectServiceServer()
}

func RegisterCommonSubjectServiceServer(s grpc.ServiceRegistrar, srv CommonSubjectServiceServer) {
	// If the following call panics, it indicates UnimplementedCommonSubjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommonSubjectService_ServiceDesc, srv)
}

func _CommonSubjectService_CreateCommonSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommonSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonSubjectServiceServer).CreateCommonSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonSubjectService_CreateCommonSubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonSubjectServiceServer).CreateCommonSubject(ctx, req.(*CreateCommonSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonSubjectService_GetCommonSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommonSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonSubjectServiceServer).GetCommonSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonSubjectService_GetCommonSubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonSubjectServiceServer).GetCommonSubject(ctx, req.(*GetCommonSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonSubjectService_GetAllCommonSubjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCommonSubjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonSubjectServiceServer).GetAllCommonSubjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonSubjectService_GetAllCommonSubjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonSubjectServiceServer).GetAllCommonSubjects(ctx, req.(*GetAllCommonSubjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonSubjectService_UpdateCommonSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommonSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonSubjectServiceServer).UpdateCommonSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonSubjectService_UpdateCommonSubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonSubjectServiceServer).UpdateCommonSubject(ctx, req.(*UpdateCommonSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonSubjectService_DeleteCommonSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommonSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonSubjectServiceServer).DeleteCommonSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonSubjectService_DeleteCommonSubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonSubjectServiceServer).DeleteCommonSubject(ctx, req.(*DeleteCommonSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommonSubjectService_ServiceDesc is the grpc.ServiceDesc for CommonSubjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommonSubjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common_subject.v1.CommonSubjectService",
	HandlerType: (*CommonSubjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCommonSubject",
			Handler:    _CommonSubjectService_CreateCommonSubject_Handler,
		},
		{
			MethodName: "GetCommonSubject",
			Handler:    _CommonSubjectService_GetCommonSubject_Handler,
		},
		{
			MethodName: "GetAllCommonSubjects",
			Handler:    _CommonSubjectService_GetAllCommonSubjects_Handler,
		},
		{
			MethodName: "UpdateCommonSubject",
			Handler:    _CommonSubjectService_UpdateCommonSubject_Handler,
		},
		{
			MethodName: "DeleteCommonSubject",
			Handler:    _CommonSubjectService_DeleteCommonSubject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common_subject/v1/common_subject.proto",
}
