// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: quiz/v1/quiz.proto

package quizv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuizService_CreateQuiz_FullMethodName    = "/quiz.v1.QuizService/CreateQuiz"
	QuizService_GetQuiz_FullMethodName       = "/quiz.v1.QuizService/GetQuiz"
	QuizService_GetAllQuizzes_FullMethodName = "/quiz.v1.QuizService/GetAllQuizzes"
	QuizService_GetMyQuizzes_FullMethodName  = "/quiz.v1.QuizService/GetMyQuizzes"
	QuizService_PublishQuiz_FullMethodName   = "/quiz.v1.QuizService/PublishQuiz"
	QuizService_UpdateQuiz_FullMethodName    = "/quiz.v1.QuizService/UpdateQuiz"
	QuizService_DeleteQuiz_FullMethodName    = "/quiz.v1.QuizService/DeleteQuiz"
)

// QuizServiceClient is the client API for QuizService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuizServiceClient interface {
	CreateQuiz(ctx context.Context, in *CreateQuizRequest, opts ...grpc.CallOption) (*QuizResponse, error)
	GetQuiz(ctx context.Context, in *GetQuizRequest, opts ...grpc.CallOption) (*QuizResponse, error)
	GetAllQuizzes(ctx context.Context, in *GetAllQuizzesRequest, opts ...grpc.CallOption) (*GetAllQuizzesResponse, error)
	GetMyQuizzes(ctx context.Context, in *GetMyQuizzesRequest, opts ...grpc.CallOption) (*GetAllQuizzesResponse, error)
	PublishQuiz(ctx context.Context, in *PublishQuizRequest, opts ...grpc.CallOption) (*PublishQuizResponse, error)
	UpdateQuiz(ctx context.Context, in *UpdateQuizRequest, opts ...grpc.CallOption) (*QuizResponse, error)
	DeleteQuiz(ctx context.Context, in *DeleteQuizRequest, opts ...grpc.CallOption) (*DeleteQuizResponse, error)
}

type quizServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuizServiceClient(cc grpc.ClientConnInterface) QuizServiceClient {
	return &quizServiceClient{cc}
}

func (c *quizServiceClient) CreateQuiz(ctx context.Context, in *CreateQuizRequest, opts ...grpc.CallOption) (*QuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuizResponse)
	err := c.cc.Invoke(ctx, QuizService_CreateQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GetQuiz(ctx context.Context, in *GetQuizRequest, opts ...grpc.CallOption) (*QuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuizResponse)
	err := c.cc.Invoke(ctx, QuizService_GetQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GetAllQuizzes(ctx context.Context, in *GetAllQuizzesRequest, opts ...grpc.CallOption) (*GetAllQuizzesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllQuizzesResponse)
	err := c.cc.Invoke(ctx, QuizService_GetAllQuizzes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) GetMyQuizzes(ctx context.Context, in *GetMyQuizzesRequest, opts ...grpc.CallOption) (*GetAllQuizzesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllQuizzesResponse)
	err := c.cc.Invoke(ctx, QuizService_GetMyQuizzes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) PublishQuiz(ctx context.Context, in *PublishQuizRequest, opts ...grpc.CallOption) (*PublishQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishQuizResponse)
	err := c.cc.Invoke(ctx, QuizService_PublishQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) UpdateQuiz(ctx context.Context, in *UpdateQuizRequest, opts ...grpc.CallOption) (*QuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuizResponse)
	err := c.cc.Invoke(ctx, QuizService_UpdateQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) DeleteQuiz(ctx context.Context, in *DeleteQuizRequest, opts ...grpc.CallOption) (*DeleteQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteQuizResponse)
	err := c.cc.Invoke(ctx, QuizService_DeleteQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuizServiceServer is the server API for QuizService service.
// All implementations must embed UnimplementedQuizServiceServer
// for forward compatibility.
type QuizServiceServer interface {
	CreateQuiz(context.Context, *CreateQuizRequest) (*QuizResponse, error)
	GetQuiz(context.Context, *GetQuizRequest) (*QuizResponse, error)
	GetAllQuizzes(context.Context, *GetAllQuizzesRequest) (*GetAllQuizzesResponse, error)
	GetMyQuizzes(context.Context, *GetMyQuizzesRequest) (*GetAllQuizzesResponse, error)
	PublishQuiz(context.Context, *PublishQuizRequest) (*PublishQuizResponse, error)
	UpdateQuiz(context.Context, *UpdateQuizRequest) (*QuizResponse, error)
	DeleteQuiz(context.Context, *DeleteQuizRequest) (*DeleteQuizResponse, error)
	mustEmbedUnimplementedQuizServiceServer()
}

// UnimplementedQuizServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuizServiceServer struct{}

func (UnimplementedQuizServiceServer) CreateQuiz(context.Context, *CreateQuizRequest) (*QuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateQuiz not implemented")
}
func (UnimplementedQuizServiceServer) GetQuiz(context.Context, *GetQuizRequest) (*QuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuiz not implemented")
}
func (UnimplementedQuizServiceServer) GetAllQuizzes(context.Context, *GetAllQuizzesRequest) (*GetAllQuizzesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllQuizzes not implemented")
}
func (UnimplementedQuizServiceServer) GetMyQuizzes(context.Context, *GetMyQuizzesRequest) (*GetAllQuizzesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyQuizzes not implemented")
}
func (UnimplementedQuizServiceServer) PublishQuiz(context.Context, *PublishQuizRequest) (*PublishQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishQuiz not implemented")
}
func (UnimplementedQuizServiceServer) UpdateQuiz(context.Context, *UpdateQuizRequest) (*QuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateQuiz not implemented")
}
func (UnimplementedQuizServiceServer) DeleteQuiz(context.Context, *DeleteQuizRequest) (*DeleteQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteQuiz not implemented")
}
func (UnimplementedQuizServiceServer) mustEmbedUnimplementedQuizServiceServer() {}
func (UnimplementedQuizServiceServer) testEmbeddedByValue()                     {}

// UnsafeQuizServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuizServiceServer will
// result in compilation errors.
type UnsafeQuizServiceServer interface {
	mustEmbedUnimplementedQuizServiceServer()
}

func RegisterQuizServiceServer(s grpc.ServiceRegistrar, srv QuizServiceServer) {
	// If the following call panics, it indicates UnimplementedQuizServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuizService_ServiceDesc, srv)
}

func _QuizService_CreateQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).CreateQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_CreateQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).CreateQuiz(ctx, req.(*CreateQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GetQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetQuiz(ctx, req.(*GetQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GetAllQuizzes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllQuizzesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetAllQuizzes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetAllQuizzes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetAllQuizzes(ctx, req.(*GetAllQuizzesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_GetMyQuizzes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyQuizzesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetMyQuizzes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetMyQuizzes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetMyQuizzes(ctx, req.(*GetMyQuizzesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_PublishQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).PublishQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_PublishQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).PublishQuiz(ctx, req.(*PublishQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_UpdateQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).UpdateQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_UpdateQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).UpdateQuiz(ctx, req.(*UpdateQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_DeleteQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).DeleteQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_DeleteQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).DeleteQuiz(ctx, req.(*DeleteQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuizService_ServiceDesc is the grpc.ServiceDesc for QuizService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuizService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.v1.QuizService",
	HandlerType: (*QuizServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuiz",
			Handler:    _QuizService_CreateQuiz_Handler,
		},
		{
			MethodName: "GetQuiz",
			Handler:    _QuizService_GetQuiz_Handler,
		},
		{
			MethodName: "GetAllQuizzes",
			Handler:    _QuizService_GetAllQuizzes_Handler,
		},
		{
			MethodName: "GetMyQuizzes",
			Handler:    _QuizService_GetMyQuizzes_Handler,
		},
		{
			MethodName: "PublishQuiz",
			Handler:    _QuizService_PublishQuiz_Handler,
		},
		{
			MethodName: "UpdateQuiz",
			Handler:    _QuizService_UpdateQuiz_Handler,
		},
		{
			MethodName: "DeleteQuiz",
			Handler:    _QuizService_DeleteQuiz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quiz/v1/quiz.proto",
}

const (
	QuestionService_CreateQuestionWithAnswers_FullMethodName = "/quiz.v1.QuestionService/CreateQuestionWithAnswers"
	QuestionService_GetQuestion_FullMethodName               = "/quiz.v1.QuestionService/GetQuestion"
	QuestionService_GetAllQuestions_FullMethodName           = "/quiz.v1.QuestionService/GetAllQuestions"
	QuestionService_UpdateQuestionWithAnswers_FullMethodName = "/quiz.v1.QuestionService/UpdateQuestionWithAnswers"
	QuestionService_DeleteQuestion_FullMethodName            = "/quiz.v1.QuestionService/DeleteQuestion"
)

// QuestionServiceClient is the client API for QuestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuestionServiceClient interface {
	CreateQuestionWithAnswers(ctx context.Context, in *CreateQuestionWithAnswersRequest, opts ...grpc.CallOption) (*QuestionWithAnswersResponse, error)
	GetQuestion(ctx context.Context, in *GetQuestionRequest, opts ...grpc.CallOption) (*QuestionWithAnswersResponse, error)
	GetAllQuestions(ctx context.Context, in *GetAllQuestionsRequest, opts ...grpc.CallOption) (*GetAllQuestionsWithAnswersResponse, error)
	UpdateQuestionWithAnswers(ctx context.Context, in *UpdateQuestionWithAnswersRequest, opts ...grpc.CallOption) (*QuestionWithAnswersResponse, error)
	DeleteQuestion(ctx context.Context, in *DeleteQuestionRequest, opts ...grpc.CallOption) (*DeleteQuestionResponse, error)
}

type questionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestionServiceClient(cc grpc.ClientConnInterface) QuestionServiceClient {
	return &questionServiceClient{cc}
}

func (c *questionServiceClient) CreateQuestionWithAnswers(ctx context.Context, in *CreateQuestionWithAnswersRequest, opts ...grpc.CallOption) (*QuestionWithAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionWithAnswersResponse)
	err := c.cc.Invoke(ctx, QuestionService_CreateQuestionWithAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiceClient) GetQuestion(ctx context.Context, in *GetQuestionRequest, opts ...grpc.CallOption) (*QuestionWithAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionWithAnswersResponse)
	err := c.cc.Invoke(ctx, QuestionService_GetQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiceClient) GetAllQuestions(ctx context.Context, in *GetAllQuestionsRequest, opts ...grpc.CallOption) (*GetAllQuestionsWithAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllQuestionsWithAnswersResponse)
	err := c.cc.Invoke(ctx, QuestionService_GetAllQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiceClient) UpdateQuestionWithAnswers(ctx context.Context, in *UpdateQuestionWithAnswersRequest, opts ...grpc.CallOption) (*QuestionWithAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionWithAnswersResponse)
	err := c.cc.Invoke(ctx, QuestionService_UpdateQuestionWithAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiceClient) DeleteQuestion(ctx context.Context, in *DeleteQuestionRequest, opts ...grpc.CallOption) (*DeleteQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteQuestionResponse)
	err := c.cc.Invoke(ctx, QuestionService_DeleteQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionServiceServer is the server API for QuestionService service.
// All implementations must embed UnimplementedQuestionServiceServer
// for forward compatibility.
type QuestionServiceServer interface {
	CreateQuestionWithAnswers(context.Context, *CreateQuestionWithAnswersRequest) (*QuestionWithAnswersResponse, error)
	GetQuestion(context.Context, *GetQuestionRequest) (*QuestionWithAnswersResponse, error)
	GetAllQuestions(context.Context, *GetAllQuestionsRequest) (*GetAllQuestionsWithAnswersResponse, error)
	UpdateQuestionWithAnswers(context.Context, *UpdateQuestionWithAnswersRequest) (*QuestionWithAnswersResponse, error)
	DeleteQuestion(context.Context, *DeleteQuestionRequest) (*DeleteQuestionResponse, error)
	mustEmbedUnimplementedQuestionServiceServer()
}

// UnimplementedQuestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuestionServiceServer struct{}

func (UnimplementedQuestionServiceServer) CreateQuestionWithAnswers(context.Context, *CreateQuestionWithAnswersRequest) (*QuestionWithAnswersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateQuestionWithAnswers not implemented")
}
func (UnimplementedQuestionServiceServer) GetQuestion(context.Context, *GetQuestionRequest) (*QuestionWithAnswersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuestion not implemented")
}
func (UnimplementedQuestionServiceServer) GetAllQuestions(context.Context, *GetAllQuestionsRequest) (*GetAllQuestionsWithAnswersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllQuestions not implemented")
}
func (UnimplementedQuestionServiceServer) UpdateQuestionWithAnswers(context.Context, *UpdateQuestionWithAnswersRequest) (*QuestionWithAnswersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateQuestionWithAnswers not implemented")
}
func (UnimplementedQuestionServiceServer) DeleteQuestion(context.Context, *DeleteQuestionRequest) (*DeleteQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteQuestion not implemented")
}
func (UnimplementedQuestionServiceServer) mustEmbedUnimplementedQuestionServiceServer() {}
func (UnimplementedQuestionServiceServer) testEmbeddedByValue()                         {}

// UnsafeQuestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestionServiceServer will
// result in compilation errors.
type UnsafeQuestionServiceServer interface {
	mustEmbedUnimplementedQuestionServiceServer()
}

func RegisterQuestionServiceServer(s grpc.ServiceRegistrar, srv QuestionServiceServer) {
	// If the following call panics, it indicates UnimplementedQuestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuestionService_ServiceDesc, srv)
}

func _QuestionService_CreateQuestionWithAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuestionWithAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiceServer).CreateQuestionWithAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestionService_CreateQuestionWithAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiceServer).CreateQuestionWithAnswers(ctx, req.(*CreateQuestionWithAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionService_GetQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiceServer).GetQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestionService_GetQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiceServer).GetQuestion(ctx, req.(*GetQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionService_GetAllQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiceServer).GetAllQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestionService_GetAllQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiceServer).GetAllQuestions(ctx, req.(*GetAllQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionService_UpdateQuestionWithAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuestionWithAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiceServer).UpdateQuestionWithAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestionService_UpdateQuestionWithAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiceServer).UpdateQuestionWithAnswers(ctx, req.(*UpdateQuestionWithAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionService_DeleteQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiceServer).DeleteQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestionService_DeleteQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiceServer).DeleteQuestion(ctx, req.(*DeleteQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuestionService_ServiceDesc is the grpc.ServiceDesc for QuestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.v1.QuestionService",
	HandlerType: (*QuestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuestionWithAnswers",
			Handler:    _QuestionService_CreateQuestionWithAnswers_Handler,
		},
		{
			MethodName: "GetQuestion",
			Handler:    _QuestionService_GetQuestion_Handler,
		},
		{
			MethodName: "GetAllQuestions",
			Handler:    _QuestionService_GetAllQuestions_Handler,
		},
		{
			MethodName: "UpdateQuestionWithAnswers",
			Handler:    _QuestionService_UpdateQuestionWithAnswers_Handler,
		},
		{
			MethodName: "DeleteQuestion",
			Handler:    _QuestionService_DeleteQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quiz/v1/quiz.proto",
}

const (
	QuizResultService_SubmitQuiz_FullMethodName     = "/quiz.v1.QuizResultService/SubmitQuiz"
	QuizResultService_GetQuizResults_FullMethodName = "/quiz.v1.QuizResultService/GetQuizResults"
)

// QuizResultServiceClient is the client API for QuizResultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuizResultServiceClient interface {
	SubmitQuiz(ctx context.Context, in *SubmitQuizRequest, opts ...grpc.CallOption) (*SubmitQuizResponse, error)
	GetQuizResults(ctx context.Context, in *GetQuizResultsRequest, opts ...grpc.CallOption) (*GetQuizResultsResponse, error)
}

type quizResultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuizResultServiceClient(cc grpc.ClientConnInterface) QuizResultServiceClient {
	return &quizResultServiceClient{cc}
}

func (c *quizResultServiceClient) SubmitQuiz(ctx context.Context, in *SubmitQuizRequest, opts ...grpc.CallOption) (*SubmitQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitQuizResponse)
	err := c.cc.Invoke(ctx, QuizResultService_SubmitQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizResultServiceClient) GetQuizResults(ctx context.Context, in *GetQuizResultsRequest, opts ...grpc.CallOption) (*GetQuizResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuizResultsResponse)
	err := c.cc.Invoke(ctx, QuizResultService_GetQuizResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuizResultServiceServer is the server API for QuizResultService service.
// All implementations must embed UnimplementedQuizResultServiceServer
// for forward compatibility.
type QuizResultServiceServer interface {
	SubmitQuiz(context.Context, *SubmitQuizRequest) (*SubmitQuizResponse, error)
	GetQuizResults(context.Context, *GetQuizResultsRequest) (*GetQuizResultsResponse, error)
	mustEmbedUnimplementedQuizResultServiceServer()
}

// UnimplementedQuizResultServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuizResultServiceServer struct{}

func (UnimplementedQuizResultServiceServer) SubmitQuiz(context.Context, *SubmitQuizRequest) (*SubmitQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitQuiz not implemented")
}
func (UnimplementedQuizResultServiceServer) GetQuizResults(context.Context, *GetQuizResultsRequest) (*GetQuizResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuizResults not implemented")
}
func (UnimplementedQuizResultServiceServer) mustEmbedUnimplementedQuizResultServiceServer() {}
func (UnimplementedQuizResultServiceServer) testEmbeddedByValue()                           {}

// UnsafeQuizResultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuizResultServiceServer will
// result in compilation errors.
type UnsafeQuizResultServiceServer interface {
	mustEmbedUnimplementedQuizResultServiceServer()
}

func RegisterQuizResultServiceServer(s grpc.ServiceRegistrar, srv QuizResultServiceServer) {
	// If the following call panics, it indicates UnimplementedQuizResultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuizResultService_ServiceDesc, srv)
}

func _QuizResultService_SubmitQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizResultServiceServer).SubmitQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizResultService_SubmitQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizResultServiceServer).SubmitQuiz(ctx, req.(*SubmitQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizResultService_GetQuizResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuizResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizResultServiceServer).GetQuizResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizResultService_GetQuizResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizResultServiceServer).GetQuizResults(ctx, req.(*GetQuizResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuizResultService_ServiceDesc is the grpc.ServiceDesc for QuizResultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuizResultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.v1.QuizResultService",
	HandlerType: (*QuizResultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitQuiz",
			Handler:    _QuizResultService_SubmitQuiz_Handler,
		},
		{
			MethodName: "GetQuizResults",
			Handler:    _QuizResultService_GetQuizResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quiz/v1/quiz.proto",
}
