// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: quiz/v1/quiz.proto

package quizv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateQuizRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Language        string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	CommonSubjectId int64                  `protobuf:"varint,4,opt,name=common_subject_id,json=commonSubjectId,proto3" json:"common_subject_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateQuizRequest) Reset() {
	*x = CreateQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizRequest) ProtoMessage() {}

func (x *CreateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizRequest.ProtoReflect.Descriptor instead.
func (*CreateQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQuizRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateQuizRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateQuizRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateQuizRequest) GetCommonSubjectId() int64 {
	if x != nil {
		return x.CommonSubjectId
	}
	return 0
}

type UpdateQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuizRequest) Reset() {
	*x = UpdateQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuizRequest) ProtoMessage() {}

func (x *UpdateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuizRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateQuizRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateQuizRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateQuizRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UpdateQuizRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizRequest) Reset() {
	*x = GetQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizRequest) ProtoMessage() {}

func (x *GetQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizRequest.ProtoReflect.Descriptor instead.
func (*GetQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuizRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllQuizzesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int32                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllQuizzesRequest) Reset() {
	*x = GetAllQuizzesRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllQuizzesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQuizzesRequest) ProtoMessage() {}

func (x *GetAllQuizzesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQuizzesRequest.ProtoReflect.Descriptor instead.
func (*GetAllQuizzesRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllQuizzesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetAllQuizzesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetAllQuizzesRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type GetMyQuizzesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int32                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyQuizzesRequest) Reset() {
	*x = GetMyQuizzesRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyQuizzesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyQuizzesRequest) ProtoMessage() {}

func (x *GetMyQuizzesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyQuizzesRequest.ProtoReflect.Descriptor instead.
func (*GetMyQuizzesRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyQuizzesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetMyQuizzesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type PublishQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishQuizRequest) Reset() {
	*x = PublishQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishQuizRequest) ProtoMessage() {}

func (x *PublishQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishQuizRequest.ProtoReflect.Descriptor instead.
func (*PublishQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *PublishQuizRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuizRequest) Reset() {
	*x = DeleteQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizRequest) ProtoMessage() {}

func (x *DeleteQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteQuizRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type QuizResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Language        string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	AuthorId        int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Type            string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	CommonSubjectId int64                  `protobuf:"varint,7,opt,name=common_subject_id,json=commonSubjectId,proto3" json:"common_subject_id,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuizResponse) Reset() {
	*x = QuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResponse) ProtoMessage() {}

func (x *QuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResponse.ProtoReflect.Descriptor instead.
func (*QuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{7}
}

func (x *QuizResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuizResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuizResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *QuizResponse) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *QuizResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QuizResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QuizResponse) GetCommonSubjectId() int64 {
	if x != nil {
		return x.CommonSubjectId
	}
	return 0
}

func (x *QuizResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *QuizResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetAllQuizzesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quizzes       []*QuizResponse        `protobuf:"bytes,1,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllQuizzesResponse) Reset() {
	*x = GetAllQuizzesResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllQuizzesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQuizzesResponse) ProtoMessage() {}

func (x *GetAllQuizzesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQuizzesResponse.ProtoReflect.Descriptor instead.
func (*GetAllQuizzesResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllQuizzesResponse) GetQuizzes() []*QuizResponse {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

type DeleteQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuizResponse) Reset() {
	*x = DeleteQuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizResponse) ProtoMessage() {}

func (x *DeleteQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteQuizResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublishQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishQuizResponse) Reset() {
	*x = PublishQuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishQuizResponse) ProtoMessage() {}

func (x *PublishQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishQuizResponse.ProtoReflect.Descriptor instead.
func (*PublishQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{10}
}

type CreateQuestionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuizId         int64                  `protobuf:"varint,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Context        string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	VideoAnswerUrl string                 `protobuf:"bytes,4,opt,name=video_answer_url,json=videoAnswerUrl,proto3" json:"video_answer_url,omitempty"`
	Order          int64                  `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{11}
}

func (x *CreateQuestionRequest) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *CreateQuestionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateQuestionRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *CreateQuestionRequest) GetVideoAnswerUrl() string {
	if x != nil {
		return x.VideoAnswerUrl
	}
	return ""
}

func (x *CreateQuestionRequest) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

type UpdateQuestionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Context        string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	VideoAnswerUrl string                 `protobuf:"bytes,4,opt,name=video_answer_url,json=videoAnswerUrl,proto3" json:"video_answer_url,omitempty"`
	Order          int64                  `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateQuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateQuestionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateQuestionRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *UpdateQuestionRequest) GetVideoAnswerUrl() string {
	if x != nil {
		return x.VideoAnswerUrl
	}
	return ""
}

func (x *UpdateQuestionRequest) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

type GetQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{13}
}

func (x *GetQuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        int64                  `protobuf:"varint,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllQuestionsRequest) Reset() {
	*x = GetAllQuestionsRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQuestionsRequest) ProtoMessage() {}

func (x *GetAllQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{14}
}

func (x *GetAllQuestionsRequest) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *GetAllQuestionsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetAllQuestionsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type DeleteQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionRequest) Reset() {
	*x = DeleteQuestionRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionRequest) ProtoMessage() {}

func (x *DeleteQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteQuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type QuestionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuizId         int64                  `protobuf:"varint,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Text           string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Context        string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	VideoAnswerUrl string                 `protobuf:"bytes,5,opt,name=video_answer_url,json=videoAnswerUrl,proto3" json:"video_answer_url,omitempty"`
	Order          int64                  `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuestionResponse) Reset() {
	*x = QuestionResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionResponse) ProtoMessage() {}

func (x *QuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionResponse.ProtoReflect.Descriptor instead.
func (*QuestionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{16}
}

func (x *QuestionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionResponse) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *QuestionResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QuestionResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *QuestionResponse) GetVideoAnswerUrl() string {
	if x != nil {
		return x.VideoAnswerUrl
	}
	return ""
}

func (x *QuestionResponse) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *QuestionResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *QuestionResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetAllQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*QuestionResponse    `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllQuestionsResponse) Reset() {
	*x = GetAllQuestionsResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQuestionsResponse) ProtoMessage() {}

func (x *GetAllQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllQuestionsResponse) GetQuestions() []*QuestionResponse {
	if x != nil {
		return x.Questions
	}
	return nil
}

type DeleteQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionResponse) Reset() {
	*x = DeleteQuestionResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionResponse) ProtoMessage() {}

func (x *DeleteQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuestionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteQuestionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Answer messages
type CreateAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Correct       bool                   `protobuf:"varint,3,opt,name=correct,proto3" json:"correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnswerRequest) Reset() {
	*x = CreateAnswerRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnswerRequest) ProtoMessage() {}

func (x *CreateAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnswerRequest.ProtoReflect.Descriptor instead.
func (*CreateAnswerRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{19}
}

func (x *CreateAnswerRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *CreateAnswerRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateAnswerRequest) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

type UpdateAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Correct       bool                   `protobuf:"varint,3,opt,name=correct,proto3" json:"correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnswerRequest) Reset() {
	*x = UpdateAnswerRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnswerRequest) ProtoMessage() {}

func (x *UpdateAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnswerRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnswerRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateAnswerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAnswerRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateAnswerRequest) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

type GetAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnswerRequest) Reset() {
	*x = GetAnswerRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerRequest) ProtoMessage() {}

func (x *GetAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerRequest.ProtoReflect.Descriptor instead.
func (*GetAnswerRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{21}
}

func (x *GetAnswerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAnswersRequest) Reset() {
	*x = GetAllAnswersRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAnswersRequest) ProtoMessage() {}

func (x *GetAllAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAnswersRequest.ProtoReflect.Descriptor instead.
func (*GetAllAnswersRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{22}
}

func (x *GetAllAnswersRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *GetAllAnswersRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetAllAnswersRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type DeleteAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnswerRequest) Reset() {
	*x = DeleteAnswerRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnswerRequest) ProtoMessage() {}

func (x *DeleteAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnswerRequest.ProtoReflect.Descriptor instead.
func (*DeleteAnswerRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteAnswerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionId    int64                  `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Correct       bool                   `protobuf:"varint,4,opt,name=correct,proto3" json:"correct,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerResponse) Reset() {
	*x = AnswerResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResponse) ProtoMessage() {}

func (x *AnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResponse.ProtoReflect.Descriptor instead.
func (*AnswerResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{24}
}

func (x *AnswerResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnswerResponse) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AnswerResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnswerResponse) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *AnswerResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AnswerResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetAllAnswersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []*AnswerResponse      `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAnswersResponse) Reset() {
	*x = GetAllAnswersResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAnswersResponse) ProtoMessage() {}

func (x *GetAllAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAnswersResponse.ProtoReflect.Descriptor instead.
func (*GetAllAnswersResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{25}
}

func (x *GetAllAnswersResponse) GetAnswers() []*AnswerResponse {
	if x != nil {
		return x.Answers
	}
	return nil
}

type DeleteAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnswerResponse) Reset() {
	*x = DeleteAnswerResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnswerResponse) ProtoMessage() {}

func (x *DeleteAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnswerResponse.ProtoReflect.Descriptor instead.
func (*DeleteAnswerResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteAnswerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AnswerSubmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerId      int64                  `protobuf:"varint,2,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerSubmission) Reset() {
	*x = AnswerSubmission{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerSubmission) ProtoMessage() {}

func (x *AnswerSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerSubmission.ProtoReflect.Descriptor instead.
func (*AnswerSubmission) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{27}
}

func (x *AnswerSubmission) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AnswerSubmission) GetAnswerId() int64 {
	if x != nil {
		return x.AnswerId
	}
	return 0
}

type SubmitQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        int64                  `protobuf:"varint,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Answers       []*AnswerSubmission    `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitQuizRequest) Reset() {
	*x = SubmitQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitQuizRequest) ProtoMessage() {}

func (x *SubmitQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitQuizRequest.ProtoReflect.Descriptor instead.
func (*SubmitQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{28}
}

func (x *SubmitQuizRequest) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *SubmitQuizRequest) GetAnswers() []*AnswerSubmission {
	if x != nil {
		return x.Answers
	}
	return nil
}

type QuestionResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	QuestionId       int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	SelectedAnswerId int64                  `protobuf:"varint,2,opt,name=selected_answer_id,json=selectedAnswerId,proto3" json:"selected_answer_id,omitempty"`
	CorrectAnswerId  int64                  `protobuf:"varint,3,opt,name=correct_answer_id,json=correctAnswerId,proto3" json:"correct_answer_id,omitempty"`
	IsCorrect        bool                   `protobuf:"varint,4,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QuestionResult) Reset() {
	*x = QuestionResult{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionResult) ProtoMessage() {}

func (x *QuestionResult) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionResult.ProtoReflect.Descriptor instead.
func (*QuestionResult) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{29}
}

func (x *QuestionResult) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *QuestionResult) GetSelectedAnswerId() int64 {
	if x != nil {
		return x.SelectedAnswerId
	}
	return 0
}

func (x *QuestionResult) GetCorrectAnswerId() int64 {
	if x != nil {
		return x.CorrectAnswerId
	}
	return 0
}

func (x *QuestionResult) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type SubmitQuizResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResultId       int64                  `protobuf:"varint,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	TotalQuestions int32                  `protobuf:"varint,2,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	CorrectAnswers int32                  `protobuf:"varint,3,opt,name=correct_answers,json=correctAnswers,proto3" json:"correct_answers,omitempty"`
	Score          float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Results        []*QuestionResult      `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitQuizResponse) Reset() {
	*x = SubmitQuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitQuizResponse) ProtoMessage() {}

func (x *SubmitQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitQuizResponse.ProtoReflect.Descriptor instead.
func (*SubmitQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{30}
}

func (x *SubmitQuizResponse) GetResultId() int64 {
	if x != nil {
		return x.ResultId
	}
	return 0
}

func (x *SubmitQuizResponse) GetTotalQuestions() int32 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *SubmitQuizResponse) GetCorrectAnswers() int32 {
	if x != nil {
		return x.CorrectAnswers
	}
	return 0
}

func (x *SubmitQuizResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitQuizResponse) GetResults() []*QuestionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetQuizResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        int64                  `protobuf:"varint,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizResultsRequest) Reset() {
	*x = GetQuizResultsRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizResultsRequest) ProtoMessage() {}

func (x *GetQuizResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizResultsRequest.ProtoReflect.Descriptor instead.
func (*GetQuizResultsRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{31}
}

func (x *GetQuizResultsRequest) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *GetQuizResultsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type QuizResultSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuizId         int64                  `protobuf:"varint,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	UserId         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score          float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	TotalQuestions int32                  `protobuf:"varint,5,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	CorrectAnswers int32                  `protobuf:"varint,6,opt,name=correct_answers,json=correctAnswers,proto3" json:"correct_answers,omitempty"`
	SubmittedAt    int64                  `protobuf:"varint,7,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuizResultSummary) Reset() {
	*x = QuizResultSummary{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResultSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResultSummary) ProtoMessage() {}

func (x *QuizResultSummary) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResultSummary.ProtoReflect.Descriptor instead.
func (*QuizResultSummary) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{32}
}

func (x *QuizResultSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuizResultSummary) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *QuizResultSummary) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *QuizResultSummary) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuizResultSummary) GetTotalQuestions() int32 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *QuizResultSummary) GetCorrectAnswers() int32 {
	if x != nil {
		return x.CorrectAnswers
	}
	return 0
}

func (x *QuizResultSummary) GetSubmittedAt() int64 {
	if x != nil {
		return x.SubmittedAt
	}
	return 0
}

type GetQuizResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*QuizResultSummary   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizResultsResponse) Reset() {
	*x = GetQuizResultsResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizResultsResponse) ProtoMessage() {}

func (x *GetQuizResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizResultsResponse.ProtoReflect.Descriptor instead.
func (*GetQuizResultsResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{33}
}

func (x *GetQuizResultsResponse) GetResults() []*QuizResultSummary {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_quiz_v1_quiz_proto protoreflect.FileDescriptor

const file_quiz_v1_quiz_proto_rawDesc = "" +
	"\n" +
	"\x12quiz/v1/quiz.proto\x12\aquiz.v1\"\x85\x01\n" +
	"\x11CreateQuizRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12*\n" +
	"\x11common_subject_id\x18\x04 \x01(\x03R\x0fcommonSubjectId\"i\n" +
	"\x11UpdateQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\" \n" +
	"\x0eGetQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8b\x01\n" +
	"\x14GetAllQuizzesRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x02R\x06status\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\t\n" +
	"\a_status\"b\n" +
	"\x13GetMyQuizzesRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"$\n" +
	"\x12PublishQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11DeleteQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x83\x02\n" +
	"\fQuizResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12*\n" +
	"\x11common_subject_id\x18\a \x01(\x03R\x0fcommonSubjectId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"H\n" +
	"\x15GetAllQuizzesResponse\x12/\n" +
	"\aquizzes\x18\x01 \x03(\v2\x15.quiz.v1.QuizResponseR\aquizzes\".\n" +
	"\x12DeleteQuizResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x15\n" +
	"\x13PublishQuizResponse\"\x9e\x01\n" +
	"\x15CreateQuestionRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\x03R\x06quizId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12(\n" +
	"\x10video_answer_url\x18\x04 \x01(\tR\x0evideoAnswerUrl\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x03R\x05order\"\x95\x01\n" +
	"\x15UpdateQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12(\n" +
	"\x10video_answer_url\x18\x04 \x01(\tR\x0evideoAnswerUrl\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x03R\x05order\"$\n" +
	"\x12GetQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"~\n" +
	"\x16GetAllQuestionsRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\x03R\x06quizId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"'\n" +
	"\x15DeleteQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe7\x01\n" +
	"\x10QuestionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\x03R\x06quizId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\x12(\n" +
	"\x10video_answer_url\x18\x05 \x01(\tR\x0evideoAnswerUrl\x12\x14\n" +
	"\x05order\x18\x06 \x01(\x03R\x05order\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"R\n" +
	"\x17GetAllQuestionsResponse\x127\n" +
	"\tquestions\x18\x01 \x03(\v2\x19.quiz.v1.QuestionResponseR\tquestions\"2\n" +
	"\x16DeleteQuestionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"d\n" +
	"\x13CreateAnswerRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\acorrect\x18\x03 \x01(\bR\acorrect\"S\n" +
	"\x13UpdateAnswerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\acorrect\x18\x03 \x01(\bR\acorrect\"\"\n" +
	"\x10GetAnswerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x84\x01\n" +
	"\x14GetAllAnswersRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"%\n" +
	"\x13DeleteAnswerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xad\x01\n" +
	"\x0eAnswerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x18\n" +
	"\acorrect\x18\x04 \x01(\bR\acorrect\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"J\n" +
	"\x15GetAllAnswersResponse\x121\n" +
	"\aanswers\x18\x01 \x03(\v2\x17.quiz.v1.AnswerResponseR\aanswers\"0\n" +
	"\x14DeleteAnswerResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"P\n" +
	"\x10AnswerSubmission\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x1b\n" +
	"\tanswer_id\x18\x02 \x01(\x03R\banswerId\"a\n" +
	"\x11SubmitQuizRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\x03R\x06quizId\x123\n" +
	"\aanswers\x18\x02 \x03(\v2\x19.quiz.v1.AnswerSubmissionR\aanswers\"\xaa\x01\n" +
	"\x0eQuestionResult\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12,\n" +
	"\x12selected_answer_id\x18\x02 \x01(\x03R\x10selectedAnswerId\x12*\n" +
	"\x11correct_answer_id\x18\x03 \x01(\x03R\x0fcorrectAnswerId\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x04 \x01(\bR\tisCorrect\"\xcc\x01\n" +
	"\x12SubmitQuizResponse\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\x03R\bresultId\x12'\n" +
	"\x0ftotal_questions\x18\x02 \x01(\x05R\x0etotalQuestions\x12'\n" +
	"\x0fcorrect_answers\x18\x03 \x01(\x05R\x0ecorrectAnswers\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x121\n" +
	"\aresults\x18\x05 \x03(\v2\x17.quiz.v1.QuestionResultR\aresults\"I\n" +
	"\x15GetQuizResultsRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\x03R\x06quizId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xe0\x01\n" +
	"\x11QuizResultSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\x03R\x06quizId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12'\n" +
	"\x0ftotal_questions\x18\x05 \x01(\x05R\x0etotalQuestions\x12'\n" +
	"\x0fcorrect_answers\x18\x06 \x01(\x05R\x0ecorrectAnswers\x12!\n" +
	"\fsubmitted_at\x18\a \x01(\x03R\vsubmittedAt\"N\n" +
	"\x16GetQuizResultsResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.quiz.v1.QuizResultSummaryR\aresults2\xf9\x03\n" +
	"\vQuizService\x12?\n" +
	"\n" +
	"CreateQuiz\x12\x1a.quiz.v1.CreateQuizRequest\x1a\x15.quiz.v1.QuizResponse\x129\n" +
	"\aGetQuiz\x12\x17.quiz.v1.GetQuizRequest\x1a\x15.quiz.v1.QuizResponse\x12N\n" +
	"\rGetAllQuizzes\x12\x1d.quiz.v1.GetAllQuizzesRequest\x1a\x1e.quiz.v1.GetAllQuizzesResponse\x12L\n" +
	"\fGetMyQuizzes\x12\x1c.quiz.v1.GetMyQuizzesRequest\x1a\x1e.quiz.v1.GetAllQuizzesResponse\x12H\n" +
	"\vPublishQuiz\x12\x1b.quiz.v1.PublishQuizRequest\x1a\x1c.quiz.v1.PublishQuizResponse\x12?\n" +
	"\n" +
	"UpdateQuiz\x12\x1a.quiz.v1.UpdateQuizRequest\x1a\x15.quiz.v1.QuizResponse\x12E\n" +
	"\n" +
	"DeleteQuiz\x12\x1a.quiz.v1.DeleteQuizRequest\x1a\x1b.quiz.v1.DeleteQuizResponse2\x9b\x03\n" +
	"\x0fQuestionService\x12K\n" +
	"\x0eCreateQuestion\x12\x1e.quiz.v1.CreateQuestionRequest\x1a\x19.quiz.v1.QuestionResponse\x12E\n" +
	"\vGetQuestion\x12\x1b.quiz.v1.GetQuestionRequest\x1a\x19.quiz.v1.QuestionResponse\x12T\n" +
	"\x0fGetAllQuestions\x12\x1f.quiz.v1.GetAllQuestionsRequest\x1a .quiz.v1.GetAllQuestionsResponse\x12K\n" +
	"\x0eUpdateQuestion\x12\x1e.quiz.v1.UpdateQuestionRequest\x1a\x19.quiz.v1.QuestionResponse\x12Q\n" +
	"\x0eDeleteQuestion\x12\x1e.quiz.v1.DeleteQuestionRequest\x1a\x1f.quiz.v1.DeleteQuestionResponse2\xfb\x02\n" +
	"\rAnswerService\x12E\n" +
	"\fCreateAnswer\x12\x1c.quiz.v1.CreateAnswerRequest\x1a\x17.quiz.v1.AnswerResponse\x12?\n" +
	"\tGetAnswer\x12\x19.quiz.v1.GetAnswerRequest\x1a\x17.quiz.v1.AnswerResponse\x12N\n" +
	"\rGetAllAnswers\x12\x1d.quiz.v1.GetAllAnswersRequest\x1a\x1e.quiz.v1.GetAllAnswersResponse\x12E\n" +
	"\fUpdateAnswer\x12\x1c.quiz.v1.UpdateAnswerRequest\x1a\x17.quiz.v1.AnswerResponse\x12K\n" +
	"\fDeleteAnswer\x12\x1c.quiz.v1.DeleteAnswerRequest\x1a\x1d.quiz.v1.DeleteAnswerResponse2\xad\x01\n" +
	"\x11QuizResultService\x12E\n" +
	"\n" +
	"SubmitQuiz\x12\x1a.quiz.v1.SubmitQuizRequest\x1a\x1b.quiz.v1.SubmitQuizResponse\x12Q\n" +
	"\x0eGetQuizResults\x12\x1e.quiz.v1.GetQuizResultsRequest\x1a\x1f.quiz.v1.GetQuizResultsResponseBBZ@github.com/Talan-Application/proto-generation/gen/quiz/v1;quizv1b\x06proto3"

var (
	file_quiz_v1_quiz_proto_rawDescOnce sync.Once
	file_quiz_v1_quiz_proto_rawDescData []byte
)

func file_quiz_v1_quiz_proto_rawDescGZIP() []byte {
	file_quiz_v1_quiz_proto_rawDescOnce.Do(func() {
		file_quiz_v1_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quiz_v1_quiz_proto_rawDesc), len(file_quiz_v1_quiz_proto_rawDesc)))
	})
	return file_quiz_v1_quiz_proto_rawDescData
}

var file_quiz_v1_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_quiz_v1_quiz_proto_goTypes = []any{
	(*CreateQuizRequest)(nil),       // 0: quiz.v1.CreateQuizRequest
	(*UpdateQuizRequest)(nil),       // 1: quiz.v1.UpdateQuizRequest
	(*GetQuizRequest)(nil),          // 2: quiz.v1.GetQuizRequest
	(*GetAllQuizzesRequest)(nil),    // 3: quiz.v1.GetAllQuizzesRequest
	(*GetMyQuizzesRequest)(nil),     // 4: quiz.v1.GetMyQuizzesRequest
	(*PublishQuizRequest)(nil),      // 5: quiz.v1.PublishQuizRequest
	(*DeleteQuizRequest)(nil),       // 6: quiz.v1.DeleteQuizRequest
	(*QuizResponse)(nil),            // 7: quiz.v1.QuizResponse
	(*GetAllQuizzesResponse)(nil),   // 8: quiz.v1.GetAllQuizzesResponse
	(*DeleteQuizResponse)(nil),      // 9: quiz.v1.DeleteQuizResponse
	(*PublishQuizResponse)(nil),     // 10: quiz.v1.PublishQuizResponse
	(*CreateQuestionRequest)(nil),   // 11: quiz.v1.CreateQuestionRequest
	(*UpdateQuestionRequest)(nil),   // 12: quiz.v1.UpdateQuestionRequest
	(*GetQuestionRequest)(nil),      // 13: quiz.v1.GetQuestionRequest
	(*GetAllQuestionsRequest)(nil),  // 14: quiz.v1.GetAllQuestionsRequest
	(*DeleteQuestionRequest)(nil),   // 15: quiz.v1.DeleteQuestionRequest
	(*QuestionResponse)(nil),        // 16: quiz.v1.QuestionResponse
	(*GetAllQuestionsResponse)(nil), // 17: quiz.v1.GetAllQuestionsResponse
	(*DeleteQuestionResponse)(nil),  // 18: quiz.v1.DeleteQuestionResponse
	(*CreateAnswerRequest)(nil),     // 19: quiz.v1.CreateAnswerRequest
	(*UpdateAnswerRequest)(nil),     // 20: quiz.v1.UpdateAnswerRequest
	(*GetAnswerRequest)(nil),        // 21: quiz.v1.GetAnswerRequest
	(*GetAllAnswersRequest)(nil),    // 22: quiz.v1.GetAllAnswersRequest
	(*DeleteAnswerRequest)(nil),     // 23: quiz.v1.DeleteAnswerRequest
	(*AnswerResponse)(nil),          // 24: quiz.v1.AnswerResponse
	(*GetAllAnswersResponse)(nil),   // 25: quiz.v1.GetAllAnswersResponse
	(*DeleteAnswerResponse)(nil),    // 26: quiz.v1.DeleteAnswerResponse
	(*AnswerSubmission)(nil),        // 27: quiz.v1.AnswerSubmission
	(*SubmitQuizRequest)(nil),       // 28: quiz.v1.SubmitQuizRequest
	(*QuestionResult)(nil),          // 29: quiz.v1.QuestionResult
	(*SubmitQuizResponse)(nil),      // 30: quiz.v1.SubmitQuizResponse
	(*GetQuizResultsRequest)(nil),   // 31: quiz.v1.GetQuizResultsRequest
	(*QuizResultSummary)(nil),       // 32: quiz.v1.QuizResultSummary
	(*GetQuizResultsResponse)(nil),  // 33: quiz.v1.GetQuizResultsResponse
}
var file_quiz_v1_quiz_proto_depIdxs = []int32{
	7,  // 0: quiz.v1.GetAllQuizzesResponse.quizzes:type_name -> quiz.v1.QuizResponse
	16, // 1: quiz.v1.GetAllQuestionsResponse.questions:type_name -> quiz.v1.QuestionResponse
	24, // 2: quiz.v1.GetAllAnswersResponse.answers:type_name -> quiz.v1.AnswerResponse
	27, // 3: quiz.v1.SubmitQuizRequest.answers:type_name -> quiz.v1.AnswerSubmission
	29, // 4: quiz.v1.SubmitQuizResponse.results:type_name -> quiz.v1.QuestionResult
	32, // 5: quiz.v1.GetQuizResultsResponse.results:type_name -> quiz.v1.QuizResultSummary
	0,  // 6: quiz.v1.QuizService.CreateQuiz:input_type -> quiz.v1.CreateQuizRequest
	2,  // 7: quiz.v1.QuizService.GetQuiz:input_type -> quiz.v1.GetQuizRequest
	3,  // 8: quiz.v1.QuizService.GetAllQuizzes:input_type -> quiz.v1.GetAllQuizzesRequest
	4,  // 9: quiz.v1.QuizService.GetMyQuizzes:input_type -> quiz.v1.GetMyQuizzesRequest
	5,  // 10: quiz.v1.QuizService.PublishQuiz:input_type -> quiz.v1.PublishQuizRequest
	1,  // 11: quiz.v1.QuizService.UpdateQuiz:input_type -> quiz.v1.UpdateQuizRequest
	6,  // 12: quiz.v1.QuizService.DeleteQuiz:input_type -> quiz.v1.DeleteQuizRequest
	11, // 13: quiz.v1.QuestionService.CreateQuestion:input_type -> quiz.v1.CreateQuestionRequest
	13, // 14: quiz.v1.QuestionService.GetQuestion:input_type -> quiz.v1.GetQuestionRequest
	14, // 15: quiz.v1.QuestionService.GetAllQuestions:input_type -> quiz.v1.GetAllQuestionsRequest
	12, // 16: quiz.v1.QuestionService.UpdateQuestion:input_type -> quiz.v1.UpdateQuestionRequest
	15, // 17: quiz.v1.QuestionService.DeleteQuestion:input_type -> quiz.v1.DeleteQuestionRequest
	19, // 18: quiz.v1.AnswerService.CreateAnswer:input_type -> quiz.v1.CreateAnswerRequest
	21, // 19: quiz.v1.AnswerService.GetAnswer:input_type -> quiz.v1.GetAnswerRequest
	22, // 20: quiz.v1.AnswerService.GetAllAnswers:input_type -> quiz.v1.GetAllAnswersRequest
	20, // 21: quiz.v1.AnswerService.UpdateAnswer:input_type -> quiz.v1.UpdateAnswerRequest
	23, // 22: quiz.v1.AnswerService.DeleteAnswer:input_type -> quiz.v1.DeleteAnswerRequest
	28, // 23: quiz.v1.QuizResultService.SubmitQuiz:input_type -> quiz.v1.SubmitQuizRequest
	31, // 24: quiz.v1.QuizResultService.GetQuizResults:input_type -> quiz.v1.GetQuizResultsRequest
	7,  // 25: quiz.v1.QuizService.CreateQuiz:output_type -> quiz.v1.QuizResponse
	7,  // 26: quiz.v1.QuizService.GetQuiz:output_type -> quiz.v1.QuizResponse
	8,  // 27: quiz.v1.QuizService.GetAllQuizzes:output_type -> quiz.v1.GetAllQuizzesResponse
	8,  // 28: quiz.v1.QuizService.GetMyQuizzes:output_type -> quiz.v1.GetAllQuizzesResponse
	10, // 29: quiz.v1.QuizService.PublishQuiz:output_type -> quiz.v1.PublishQuizResponse
	7,  // 30: quiz.v1.QuizService.UpdateQuiz:output_type -> quiz.v1.QuizResponse
	9,  // 31: quiz.v1.QuizService.DeleteQuiz:output_type -> quiz.v1.DeleteQuizResponse
	16, // 32: quiz.v1.QuestionService.CreateQuestion:output_type -> quiz.v1.QuestionResponse
	16, // 33: quiz.v1.QuestionService.GetQuestion:output_type -> quiz.v1.QuestionResponse
	17, // 34: quiz.v1.QuestionService.GetAllQuestions:output_type -> quiz.v1.GetAllQuestionsResponse
	16, // 35: quiz.v1.QuestionService.UpdateQuestion:output_type -> quiz.v1.QuestionResponse
	18, // 36: quiz.v1.QuestionService.DeleteQuestion:output_type -> quiz.v1.DeleteQuestionResponse
	24, // 37: quiz.v1.AnswerService.CreateAnswer:output_type -> quiz.v1.AnswerResponse
	24, // 38: quiz.v1.AnswerService.GetAnswer:output_type -> quiz.v1.AnswerResponse
	25, // 39: quiz.v1.AnswerService.GetAllAnswers:output_type -> quiz.v1.GetAllAnswersResponse
	24, // 40: quiz.v1.AnswerService.UpdateAnswer:output_type -> quiz.v1.AnswerResponse
	26, // 41: quiz.v1.AnswerService.DeleteAnswer:output_type -> quiz.v1.DeleteAnswerResponse
	30, // 42: quiz.v1.QuizResultService.SubmitQuiz:output_type -> quiz.v1.SubmitQuizResponse
	33, // 43: quiz.v1.QuizResultService.GetQuizResults:output_type -> quiz.v1.GetQuizResultsResponse
	25, // [25:44] is the sub-list for method output_type
	6,  // [6:25] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_quiz_v1_quiz_proto_init() }
func file_quiz_v1_quiz_proto_init() {
	if File_quiz_v1_quiz_proto != nil {
		return
	}
	file_quiz_v1_quiz_proto_msgTypes[3].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[4].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[14].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quiz_v1_quiz_proto_rawDesc), len(file_quiz_v1_quiz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_quiz_v1_quiz_proto_goTypes,
		DependencyIndexes: file_quiz_v1_quiz_proto_depIdxs,
		MessageInfos:      file_quiz_v1_quiz_proto_msgTypes,
	}.Build()
	File_quiz_v1_quiz_proto = out.File
	file_quiz_v1_quiz_proto_goTypes = nil
	file_quiz_v1_quiz_proto_depIdxs = nil
}
