// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: quiz/v1/quiz.proto

package quizv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateQuizRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Language        string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	CommonSubjectId int64                  `protobuf:"varint,4,opt,name=common_subject_id,json=commonSubjectId,proto3" json:"common_subject_id,omitempty"`
	IsEntStandard   bool                   `protobuf:"varint,5,opt,name=is_ent_standard,json=isEntStandard,proto3" json:"is_ent_standard,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateQuizRequest) Reset() {
	*x = CreateQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizRequest) ProtoMessage() {}

func (x *CreateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizRequest.ProtoReflect.Descriptor instead.
func (*CreateQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQuizRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateQuizRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateQuizRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateQuizRequest) GetCommonSubjectId() int64 {
	if x != nil {
		return x.CommonSubjectId
	}
	return 0
}

func (x *CreateQuizRequest) GetIsEntStandard() bool {
	if x != nil {
		return x.IsEntStandard
	}
	return false
}

type UpdateQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	IsEntStandard bool                   `protobuf:"varint,5,opt,name=is_ent_standard,json=isEntStandard,proto3" json:"is_ent_standard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuizRequest) Reset() {
	*x = UpdateQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuizRequest) ProtoMessage() {}

func (x *UpdateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuizRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateQuizRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateQuizRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateQuizRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UpdateQuizRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateQuizRequest) GetIsEntStandard() bool {
	if x != nil {
		return x.IsEntStandard
	}
	return false
}

type GetQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizRequest) Reset() {
	*x = GetQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizRequest) ProtoMessage() {}

func (x *GetQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizRequest.ProtoReflect.Descriptor instead.
func (*GetQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuizRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllQuizzesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int32                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllQuizzesRequest) Reset() {
	*x = GetAllQuizzesRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllQuizzesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQuizzesRequest) ProtoMessage() {}

func (x *GetAllQuizzesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQuizzesRequest.ProtoReflect.Descriptor instead.
func (*GetAllQuizzesRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllQuizzesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetAllQuizzesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetAllQuizzesRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type GetMyQuizzesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int32                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyQuizzesRequest) Reset() {
	*x = GetMyQuizzesRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyQuizzesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyQuizzesRequest) ProtoMessage() {}

func (x *GetMyQuizzesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyQuizzesRequest.ProtoReflect.Descriptor instead.
func (*GetMyQuizzesRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyQuizzesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetMyQuizzesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type PublishQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishQuizRequest) Reset() {
	*x = PublishQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishQuizRequest) ProtoMessage() {}

func (x *PublishQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishQuizRequest.ProtoReflect.Descriptor instead.
func (*PublishQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *PublishQuizRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuizRequest) Reset() {
	*x = DeleteQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizRequest) ProtoMessage() {}

func (x *DeleteQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteQuizRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type QuizResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Language        string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	AuthorId        int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Type            string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	CommonSubjectId int64                  `protobuf:"varint,7,opt,name=common_subject_id,json=commonSubjectId,proto3" json:"common_subject_id,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsEntStandard   bool                   `protobuf:"varint,10,opt,name=is_ent_standard,json=isEntStandard,proto3" json:"is_ent_standard,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuizResponse) Reset() {
	*x = QuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResponse) ProtoMessage() {}

func (x *QuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResponse.ProtoReflect.Descriptor instead.
func (*QuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{7}
}

func (x *QuizResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuizResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuizResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *QuizResponse) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *QuizResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QuizResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QuizResponse) GetCommonSubjectId() int64 {
	if x != nil {
		return x.CommonSubjectId
	}
	return 0
}

func (x *QuizResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *QuizResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *QuizResponse) GetIsEntStandard() bool {
	if x != nil {
		return x.IsEntStandard
	}
	return false
}

type GetAllQuizzesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quizzes       []*QuizResponse        `protobuf:"bytes,1,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllQuizzesResponse) Reset() {
	*x = GetAllQuizzesResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllQuizzesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQuizzesResponse) ProtoMessage() {}

func (x *GetAllQuizzesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQuizzesResponse.ProtoReflect.Descriptor instead.
func (*GetAllQuizzesResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllQuizzesResponse) GetQuizzes() []*QuizResponse {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

type DeleteQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuizResponse) Reset() {
	*x = DeleteQuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizResponse) ProtoMessage() {}

func (x *DeleteQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteQuizResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublishQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishQuizResponse) Reset() {
	*x = PublishQuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishQuizResponse) ProtoMessage() {}

func (x *PublishQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishQuizResponse.ProtoReflect.Descriptor instead.
func (*PublishQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{10}
}

type AnswerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Correct       bool                   `protobuf:"varint,2,opt,name=correct,proto3" json:"correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerInput) Reset() {
	*x = AnswerInput{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerInput) ProtoMessage() {}

func (x *AnswerInput) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerInput.ProtoReflect.Descriptor instead.
func (*AnswerInput) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{11}
}

func (x *AnswerInput) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnswerInput) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

type CreateQuestionWithAnswersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuizId         int64                  `protobuf:"varint,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Context        string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	VideoAnswerUrl string                 `protobuf:"bytes,4,opt,name=video_answer_url,json=videoAnswerUrl,proto3" json:"video_answer_url,omitempty"`
	Order          int64                  `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	Answers        []*AnswerInput         `protobuf:"bytes,6,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateQuestionWithAnswersRequest) Reset() {
	*x = CreateQuestionWithAnswersRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionWithAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionWithAnswersRequest) ProtoMessage() {}

func (x *CreateQuestionWithAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionWithAnswersRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionWithAnswersRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{12}
}

func (x *CreateQuestionWithAnswersRequest) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *CreateQuestionWithAnswersRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateQuestionWithAnswersRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *CreateQuestionWithAnswersRequest) GetVideoAnswerUrl() string {
	if x != nil {
		return x.VideoAnswerUrl
	}
	return ""
}

func (x *CreateQuestionWithAnswersRequest) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *CreateQuestionWithAnswersRequest) GetAnswers() []*AnswerInput {
	if x != nil {
		return x.Answers
	}
	return nil
}

type UpdateQuestionWithAnswersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Context        string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	VideoAnswerUrl string                 `protobuf:"bytes,4,opt,name=video_answer_url,json=videoAnswerUrl,proto3" json:"video_answer_url,omitempty"`
	Order          int64                  `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	Answers        []*AnswerInput         `protobuf:"bytes,6,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateQuestionWithAnswersRequest) Reset() {
	*x = UpdateQuestionWithAnswersRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionWithAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionWithAnswersRequest) ProtoMessage() {}

func (x *UpdateQuestionWithAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionWithAnswersRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionWithAnswersRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateQuestionWithAnswersRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateQuestionWithAnswersRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateQuestionWithAnswersRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *UpdateQuestionWithAnswersRequest) GetVideoAnswerUrl() string {
	if x != nil {
		return x.VideoAnswerUrl
	}
	return ""
}

func (x *UpdateQuestionWithAnswersRequest) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *UpdateQuestionWithAnswersRequest) GetAnswers() []*AnswerInput {
	if x != nil {
		return x.Answers
	}
	return nil
}

type QuestionWithAnswersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuizId         int64                  `protobuf:"varint,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Text           string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Context        string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	VideoAnswerUrl string                 `protobuf:"bytes,5,opt,name=video_answer_url,json=videoAnswerUrl,proto3" json:"video_answer_url,omitempty"`
	Order          int64                  `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Answers        []*AnswerResponse      `protobuf:"bytes,9,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuestionWithAnswersResponse) Reset() {
	*x = QuestionWithAnswersResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionWithAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionWithAnswersResponse) ProtoMessage() {}

func (x *QuestionWithAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionWithAnswersResponse.ProtoReflect.Descriptor instead.
func (*QuestionWithAnswersResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{14}
}

func (x *QuestionWithAnswersResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionWithAnswersResponse) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *QuestionWithAnswersResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QuestionWithAnswersResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *QuestionWithAnswersResponse) GetVideoAnswerUrl() string {
	if x != nil {
		return x.VideoAnswerUrl
	}
	return ""
}

func (x *QuestionWithAnswersResponse) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *QuestionWithAnswersResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *QuestionWithAnswersResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *QuestionWithAnswersResponse) GetAnswers() []*AnswerResponse {
	if x != nil {
		return x.Answers
	}
	return nil
}

type GetQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{15}
}

func (x *GetQuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        int64                  `protobuf:"varint,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllQuestionsRequest) Reset() {
	*x = GetAllQuestionsRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQuestionsRequest) ProtoMessage() {}

func (x *GetAllQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{16}
}

func (x *GetAllQuestionsRequest) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *GetAllQuestionsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetAllQuestionsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type DeleteQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionRequest) Reset() {
	*x = DeleteQuestionRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionRequest) ProtoMessage() {}

func (x *DeleteQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteQuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllQuestionsWithAnswersResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Questions     []*QuestionWithAnswersResponse `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllQuestionsWithAnswersResponse) Reset() {
	*x = GetAllQuestionsWithAnswersResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllQuestionsWithAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQuestionsWithAnswersResponse) ProtoMessage() {}

func (x *GetAllQuestionsWithAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQuestionsWithAnswersResponse.ProtoReflect.Descriptor instead.
func (*GetAllQuestionsWithAnswersResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{18}
}

func (x *GetAllQuestionsWithAnswersResponse) GetQuestions() []*QuestionWithAnswersResponse {
	if x != nil {
		return x.Questions
	}
	return nil
}

type DeleteQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionResponse) Reset() {
	*x = DeleteQuestionResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionResponse) ProtoMessage() {}

func (x *DeleteQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuestionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteQuestionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionId    int64                  `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Correct       bool                   `protobuf:"varint,4,opt,name=correct,proto3" json:"correct,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerResponse) Reset() {
	*x = AnswerResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResponse) ProtoMessage() {}

func (x *AnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResponse.ProtoReflect.Descriptor instead.
func (*AnswerResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{20}
}

func (x *AnswerResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnswerResponse) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AnswerResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnswerResponse) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *AnswerResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AnswerResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AnswerSubmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerIds     []int64                `protobuf:"varint,2,rep,packed,name=answer_ids,json=answerIds,proto3" json:"answer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerSubmission) Reset() {
	*x = AnswerSubmission{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerSubmission) ProtoMessage() {}

func (x *AnswerSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerSubmission.ProtoReflect.Descriptor instead.
func (*AnswerSubmission) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{21}
}

func (x *AnswerSubmission) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AnswerSubmission) GetAnswerIds() []int64 {
	if x != nil {
		return x.AnswerIds
	}
	return nil
}

type SubmitQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        int64                  `protobuf:"varint,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Answers       []*AnswerSubmission    `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitQuizRequest) Reset() {
	*x = SubmitQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitQuizRequest) ProtoMessage() {}

func (x *SubmitQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitQuizRequest.ProtoReflect.Descriptor instead.
func (*SubmitQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{22}
}

func (x *SubmitQuizRequest) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *SubmitQuizRequest) GetAnswers() []*AnswerSubmission {
	if x != nil {
		return x.Answers
	}
	return nil
}

type QuestionResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QuestionId        int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	SelectedAnswerIds []int64                `protobuf:"varint,2,rep,packed,name=selected_answer_ids,json=selectedAnswerIds,proto3" json:"selected_answer_ids,omitempty"`
	CorrectAnswerIds  []int64                `protobuf:"varint,3,rep,packed,name=correct_answer_ids,json=correctAnswerIds,proto3" json:"correct_answer_ids,omitempty"`
	Score             float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	MaxScore          float64                `protobuf:"fixed64,5,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QuestionResult) Reset() {
	*x = QuestionResult{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionResult) ProtoMessage() {}

func (x *QuestionResult) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionResult.ProtoReflect.Descriptor instead.
func (*QuestionResult) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{23}
}

func (x *QuestionResult) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *QuestionResult) GetSelectedAnswerIds() []int64 {
	if x != nil {
		return x.SelectedAnswerIds
	}
	return nil
}

func (x *QuestionResult) GetCorrectAnswerIds() []int64 {
	if x != nil {
		return x.CorrectAnswerIds
	}
	return nil
}

func (x *QuestionResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuestionResult) GetMaxScore() float64 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

type SubmitQuizResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ResultId              int64                  `protobuf:"varint,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	TotalQuestionsCount   int32                  `protobuf:"varint,2,opt,name=total_questions_count,json=totalQuestionsCount,proto3" json:"total_questions_count,omitempty"`
	CorrectAnswersCount   int32                  `protobuf:"varint,3,opt,name=correct_answers_count,json=correctAnswersCount,proto3" json:"correct_answers_count,omitempty"`
	IncorrectAnswersCount int32                  `protobuf:"varint,4,opt,name=incorrect_answers_count,json=incorrectAnswersCount,proto3" json:"incorrect_answers_count,omitempty"`
	UnansweredQuestions   int32                  `protobuf:"varint,5,opt,name=unanswered_questions,json=unansweredQuestions,proto3" json:"unanswered_questions,omitempty"`
	Score                 float64                `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	MaxScore              float64                `protobuf:"fixed64,7,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	Results               []*QuestionResult      `protobuf:"bytes,8,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SubmitQuizResponse) Reset() {
	*x = SubmitQuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitQuizResponse) ProtoMessage() {}

func (x *SubmitQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitQuizResponse.ProtoReflect.Descriptor instead.
func (*SubmitQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{24}
}

func (x *SubmitQuizResponse) GetResultId() int64 {
	if x != nil {
		return x.ResultId
	}
	return 0
}

func (x *SubmitQuizResponse) GetTotalQuestionsCount() int32 {
	if x != nil {
		return x.TotalQuestionsCount
	}
	return 0
}

func (x *SubmitQuizResponse) GetCorrectAnswersCount() int32 {
	if x != nil {
		return x.CorrectAnswersCount
	}
	return 0
}

func (x *SubmitQuizResponse) GetIncorrectAnswersCount() int32 {
	if x != nil {
		return x.IncorrectAnswersCount
	}
	return 0
}

func (x *SubmitQuizResponse) GetUnansweredQuestions() int32 {
	if x != nil {
		return x.UnansweredQuestions
	}
	return 0
}

func (x *SubmitQuizResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitQuizResponse) GetMaxScore() float64 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *SubmitQuizResponse) GetResults() []*QuestionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetQuizResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        int64                  `protobuf:"varint,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizResultsRequest) Reset() {
	*x = GetQuizResultsRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizResultsRequest) ProtoMessage() {}

func (x *GetQuizResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizResultsRequest.ProtoReflect.Descriptor instead.
func (*GetQuizResultsRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{25}
}

func (x *GetQuizResultsRequest) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *GetQuizResultsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type QuizResultSummary struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuizId                int64                  `protobuf:"varint,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	UserId                int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score                 float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	MaxScore              float64                `protobuf:"fixed64,5,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	TotalQuestionsCount   int32                  `protobuf:"varint,6,opt,name=total_questions_count,json=totalQuestionsCount,proto3" json:"total_questions_count,omitempty"`
	CorrectAnswersCount   int32                  `protobuf:"varint,7,opt,name=correct_answers_count,json=correctAnswersCount,proto3" json:"correct_answers_count,omitempty"`
	IncorrectAnswersCount int32                  `protobuf:"varint,8,opt,name=incorrect_answers_count,json=incorrectAnswersCount,proto3" json:"incorrect_answers_count,omitempty"`
	UnansweredQuestions   int32                  `protobuf:"varint,9,opt,name=unanswered_questions,json=unansweredQuestions,proto3" json:"unanswered_questions,omitempty"`
	SubmittedAt           int64                  `protobuf:"varint,10,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QuizResultSummary) Reset() {
	*x = QuizResultSummary{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResultSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResultSummary) ProtoMessage() {}

func (x *QuizResultSummary) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResultSummary.ProtoReflect.Descriptor instead.
func (*QuizResultSummary) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{26}
}

func (x *QuizResultSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuizResultSummary) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *QuizResultSummary) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *QuizResultSummary) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuizResultSummary) GetMaxScore() float64 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *QuizResultSummary) GetTotalQuestionsCount() int32 {
	if x != nil {
		return x.TotalQuestionsCount
	}
	return 0
}

func (x *QuizResultSummary) GetCorrectAnswersCount() int32 {
	if x != nil {
		return x.CorrectAnswersCount
	}
	return 0
}

func (x *QuizResultSummary) GetIncorrectAnswersCount() int32 {
	if x != nil {
		return x.IncorrectAnswersCount
	}
	return 0
}

func (x *QuizResultSummary) GetUnansweredQuestions() int32 {
	if x != nil {
		return x.UnansweredQuestions
	}
	return 0
}

func (x *QuizResultSummary) GetSubmittedAt() int64 {
	if x != nil {
		return x.SubmittedAt
	}
	return 0
}

type GetQuizResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*QuizResultSummary   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizResultsResponse) Reset() {
	*x = GetQuizResultsResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizResultsResponse) ProtoMessage() {}

func (x *GetQuizResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizResultsResponse.ProtoReflect.Descriptor instead.
func (*GetQuizResultsResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{27}
}

func (x *GetQuizResultsResponse) GetResults() []*QuizResultSummary {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_quiz_v1_quiz_proto protoreflect.FileDescriptor

const file_quiz_v1_quiz_proto_rawDesc = "" +
	"\n" +
	"\x12quiz/v1/quiz.proto\x12\aquiz.v1\"\xad\x01\n" +
	"\x11CreateQuizRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12*\n" +
	"\x11common_subject_id\x18\x04 \x01(\x03R\x0fcommonSubjectId\x12&\n" +
	"\x0fis_ent_standard\x18\x05 \x01(\bR\risEntStandard\"\x91\x01\n" +
	"\x11UpdateQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12&\n" +
	"\x0fis_ent_standard\x18\x05 \x01(\bR\risEntStandard\" \n" +
	"\x0eGetQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8b\x01\n" +
	"\x14GetAllQuizzesRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x02R\x06status\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\t\n" +
	"\a_status\"b\n" +
	"\x13GetMyQuizzesRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"$\n" +
	"\x12PublishQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11DeleteQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xab\x02\n" +
	"\fQuizResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12*\n" +
	"\x11common_subject_id\x18\a \x01(\x03R\x0fcommonSubjectId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12&\n" +
	"\x0fis_ent_standard\x18\n" +
	" \x01(\bR\risEntStandard\"H\n" +
	"\x15GetAllQuizzesResponse\x12/\n" +
	"\aquizzes\x18\x01 \x03(\v2\x15.quiz.v1.QuizResponseR\aquizzes\".\n" +
	"\x12DeleteQuizResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x15\n" +
	"\x13PublishQuizResponse\";\n" +
	"\vAnswerInput\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n" +
	"\acorrect\x18\x02 \x01(\bR\acorrect\"\xd9\x01\n" +
	" CreateQuestionWithAnswersRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\x03R\x06quizId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12(\n" +
	"\x10video_answer_url\x18\x04 \x01(\tR\x0evideoAnswerUrl\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x03R\x05order\x12.\n" +
	"\aanswers\x18\x06 \x03(\v2\x14.quiz.v1.AnswerInputR\aanswers\"\xd0\x01\n" +
	" UpdateQuestionWithAnswersRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12(\n" +
	"\x10video_answer_url\x18\x04 \x01(\tR\x0evideoAnswerUrl\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x03R\x05order\x12.\n" +
	"\aanswers\x18\x06 \x03(\v2\x14.quiz.v1.AnswerInputR\aanswers\"\xa5\x02\n" +
	"\x1bQuestionWithAnswersResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\x03R\x06quizId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\x12(\n" +
	"\x10video_answer_url\x18\x05 \x01(\tR\x0evideoAnswerUrl\x12\x14\n" +
	"\x05order\x18\x06 \x01(\x03R\x05order\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x121\n" +
	"\aanswers\x18\t \x03(\v2\x17.quiz.v1.AnswerResponseR\aanswers\"$\n" +
	"\x12GetQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"~\n" +
	"\x16GetAllQuestionsRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\x03R\x06quizId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"'\n" +
	"\x15DeleteQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"h\n" +
	"\"GetAllQuestionsWithAnswersResponse\x12B\n" +
	"\tquestions\x18\x01 \x03(\v2$.quiz.v1.QuestionWithAnswersResponseR\tquestions\"2\n" +
	"\x16DeleteQuestionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xad\x01\n" +
	"\x0eAnswerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x18\n" +
	"\acorrect\x18\x04 \x01(\bR\acorrect\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"R\n" +
	"\x10AnswerSubmission\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x1d\n" +
	"\n" +
	"answer_ids\x18\x02 \x03(\x03R\tanswerIds\"a\n" +
	"\x11SubmitQuizRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\x03R\x06quizId\x123\n" +
	"\aanswers\x18\x02 \x03(\v2\x19.quiz.v1.AnswerSubmissionR\aanswers\"\xc2\x01\n" +
	"\x0eQuestionResult\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12.\n" +
	"\x13selected_answer_ids\x18\x02 \x03(\x03R\x11selectedAnswerIds\x12,\n" +
	"\x12correct_answer_ids\x18\x03 \x03(\x03R\x10correctAnswerIds\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x1b\n" +
	"\tmax_score\x18\x05 \x01(\x01R\bmaxScore\"\xea\x02\n" +
	"\x12SubmitQuizResponse\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\x03R\bresultId\x122\n" +
	"\x15total_questions_count\x18\x02 \x01(\x05R\x13totalQuestionsCount\x122\n" +
	"\x15correct_answers_count\x18\x03 \x01(\x05R\x13correctAnswersCount\x126\n" +
	"\x17incorrect_answers_count\x18\x04 \x01(\x05R\x15incorrectAnswersCount\x121\n" +
	"\x14unanswered_questions\x18\x05 \x01(\x05R\x13unansweredQuestions\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\x12\x1b\n" +
	"\tmax_score\x18\a \x01(\x01R\bmaxScore\x121\n" +
	"\aresults\x18\b \x03(\v2\x17.quiz.v1.QuestionResultR\aresults\"I\n" +
	"\x15GetQuizResultsRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\x03R\x06quizId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xfe\x02\n" +
	"\x11QuizResultSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\x03R\x06quizId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x1b\n" +
	"\tmax_score\x18\x05 \x01(\x01R\bmaxScore\x122\n" +
	"\x15total_questions_count\x18\x06 \x01(\x05R\x13totalQuestionsCount\x122\n" +
	"\x15correct_answers_count\x18\a \x01(\x05R\x13correctAnswersCount\x126\n" +
	"\x17incorrect_answers_count\x18\b \x01(\x05R\x15incorrectAnswersCount\x121\n" +
	"\x14unanswered_questions\x18\t \x01(\x05R\x13unansweredQuestions\x12!\n" +
	"\fsubmitted_at\x18\n" +
	" \x01(\x03R\vsubmittedAt\"N\n" +
	"\x16GetQuizResultsResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.quiz.v1.QuizResultSummaryR\aresults2\xf9\x03\n" +
	"\vQuizService\x12?\n" +
	"\n" +
	"CreateQuiz\x12\x1a.quiz.v1.CreateQuizRequest\x1a\x15.quiz.v1.QuizResponse\x129\n" +
	"\aGetQuiz\x12\x17.quiz.v1.GetQuizRequest\x1a\x15.quiz.v1.QuizResponse\x12N\n" +
	"\rGetAllQuizzes\x12\x1d.quiz.v1.GetAllQuizzesRequest\x1a\x1e.quiz.v1.GetAllQuizzesResponse\x12L\n" +
	"\fGetMyQuizzes\x12\x1c.quiz.v1.GetMyQuizzesRequest\x1a\x1e.quiz.v1.GetAllQuizzesResponse\x12H\n" +
	"\vPublishQuiz\x12\x1b.quiz.v1.PublishQuizRequest\x1a\x1c.quiz.v1.PublishQuizResponse\x12?\n" +
	"\n" +
	"UpdateQuiz\x12\x1a.quiz.v1.UpdateQuizRequest\x1a\x15.quiz.v1.QuizResponse\x12E\n" +
	"\n" +
	"DeleteQuiz\x12\x1a.quiz.v1.DeleteQuizRequest\x1a\x1b.quiz.v1.DeleteQuizResponse2\xf3\x03\n" +
	"\x0fQuestionService\x12l\n" +
	"\x19CreateQuestionWithAnswers\x12).quiz.v1.CreateQuestionWithAnswersRequest\x1a$.quiz.v1.QuestionWithAnswersResponse\x12P\n" +
	"\vGetQuestion\x12\x1b.quiz.v1.GetQuestionRequest\x1a$.quiz.v1.QuestionWithAnswersResponse\x12_\n" +
	"\x0fGetAllQuestions\x12\x1f.quiz.v1.GetAllQuestionsRequest\x1a+.quiz.v1.GetAllQuestionsWithAnswersResponse\x12l\n" +
	"\x19UpdateQuestionWithAnswers\x12).quiz.v1.UpdateQuestionWithAnswersRequest\x1a$.quiz.v1.QuestionWithAnswersResponse\x12Q\n" +
	"\x0eDeleteQuestion\x12\x1e.quiz.v1.DeleteQuestionRequest\x1a\x1f.quiz.v1.DeleteQuestionResponse2\xad\x01\n" +
	"\x11QuizResultService\x12E\n" +
	"\n" +
	"SubmitQuiz\x12\x1a.quiz.v1.SubmitQuizRequest\x1a\x1b.quiz.v1.SubmitQuizResponse\x12Q\n" +
	"\x0eGetQuizResults\x12\x1e.quiz.v1.GetQuizResultsRequest\x1a\x1f.quiz.v1.GetQuizResultsResponseB>Z<github.com/Talan-Application/proto-generation/quiz/v1;quizv1b\x06proto3"

var (
	file_quiz_v1_quiz_proto_rawDescOnce sync.Once
	file_quiz_v1_quiz_proto_rawDescData []byte
)

func file_quiz_v1_quiz_proto_rawDescGZIP() []byte {
	file_quiz_v1_quiz_proto_rawDescOnce.Do(func() {
		file_quiz_v1_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quiz_v1_quiz_proto_rawDesc), len(file_quiz_v1_quiz_proto_rawDesc)))
	})
	return file_quiz_v1_quiz_proto_rawDescData
}

var file_quiz_v1_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_quiz_v1_quiz_proto_goTypes = []any{
	(*CreateQuizRequest)(nil),                  // 0: quiz.v1.CreateQuizRequest
	(*UpdateQuizRequest)(nil),                  // 1: quiz.v1.UpdateQuizRequest
	(*GetQuizRequest)(nil),                     // 2: quiz.v1.GetQuizRequest
	(*GetAllQuizzesRequest)(nil),               // 3: quiz.v1.GetAllQuizzesRequest
	(*GetMyQuizzesRequest)(nil),                // 4: quiz.v1.GetMyQuizzesRequest
	(*PublishQuizRequest)(nil),                 // 5: quiz.v1.PublishQuizRequest
	(*DeleteQuizRequest)(nil),                  // 6: quiz.v1.DeleteQuizRequest
	(*QuizResponse)(nil),                       // 7: quiz.v1.QuizResponse
	(*GetAllQuizzesResponse)(nil),              // 8: quiz.v1.GetAllQuizzesResponse
	(*DeleteQuizResponse)(nil),                 // 9: quiz.v1.DeleteQuizResponse
	(*PublishQuizResponse)(nil),                // 10: quiz.v1.PublishQuizResponse
	(*AnswerInput)(nil),                        // 11: quiz.v1.AnswerInput
	(*CreateQuestionWithAnswersRequest)(nil),   // 12: quiz.v1.CreateQuestionWithAnswersRequest
	(*UpdateQuestionWithAnswersRequest)(nil),   // 13: quiz.v1.UpdateQuestionWithAnswersRequest
	(*QuestionWithAnswersResponse)(nil),        // 14: quiz.v1.QuestionWithAnswersResponse
	(*GetQuestionRequest)(nil),                 // 15: quiz.v1.GetQuestionRequest
	(*GetAllQuestionsRequest)(nil),             // 16: quiz.v1.GetAllQuestionsRequest
	(*DeleteQuestionRequest)(nil),              // 17: quiz.v1.DeleteQuestionRequest
	(*GetAllQuestionsWithAnswersResponse)(nil), // 18: quiz.v1.GetAllQuestionsWithAnswersResponse
	(*DeleteQuestionResponse)(nil),             // 19: quiz.v1.DeleteQuestionResponse
	(*AnswerResponse)(nil),                     // 20: quiz.v1.AnswerResponse
	(*AnswerSubmission)(nil),                   // 21: quiz.v1.AnswerSubmission
	(*SubmitQuizRequest)(nil),                  // 22: quiz.v1.SubmitQuizRequest
	(*QuestionResult)(nil),                     // 23: quiz.v1.QuestionResult
	(*SubmitQuizResponse)(nil),                 // 24: quiz.v1.SubmitQuizResponse
	(*GetQuizResultsRequest)(nil),              // 25: quiz.v1.GetQuizResultsRequest
	(*QuizResultSummary)(nil),                  // 26: quiz.v1.QuizResultSummary
	(*GetQuizResultsResponse)(nil),             // 27: quiz.v1.GetQuizResultsResponse
}
var file_quiz_v1_quiz_proto_depIdxs = []int32{
	7,  // 0: quiz.v1.GetAllQuizzesResponse.quizzes:type_name -> quiz.v1.QuizResponse
	11, // 1: quiz.v1.CreateQuestionWithAnswersRequest.answers:type_name -> quiz.v1.AnswerInput
	11, // 2: quiz.v1.UpdateQuestionWithAnswersRequest.answers:type_name -> quiz.v1.AnswerInput
	20, // 3: quiz.v1.QuestionWithAnswersResponse.answers:type_name -> quiz.v1.AnswerResponse
	14, // 4: quiz.v1.GetAllQuestionsWithAnswersResponse.questions:type_name -> quiz.v1.QuestionWithAnswersResponse
	21, // 5: quiz.v1.SubmitQuizRequest.answers:type_name -> quiz.v1.AnswerSubmission
	23, // 6: quiz.v1.SubmitQuizResponse.results:type_name -> quiz.v1.QuestionResult
	26, // 7: quiz.v1.GetQuizResultsResponse.results:type_name -> quiz.v1.QuizResultSummary
	0,  // 8: quiz.v1.QuizService.CreateQuiz:input_type -> quiz.v1.CreateQuizRequest
	2,  // 9: quiz.v1.QuizService.GetQuiz:input_type -> quiz.v1.GetQuizRequest
	3,  // 10: quiz.v1.QuizService.GetAllQuizzes:input_type -> quiz.v1.GetAllQuizzesRequest
	4,  // 11: quiz.v1.QuizService.GetMyQuizzes:input_type -> quiz.v1.GetMyQuizzesRequest
	5,  // 12: quiz.v1.QuizService.PublishQuiz:input_type -> quiz.v1.PublishQuizRequest
	1,  // 13: quiz.v1.QuizService.UpdateQuiz:input_type -> quiz.v1.UpdateQuizRequest
	6,  // 14: quiz.v1.QuizService.DeleteQuiz:input_type -> quiz.v1.DeleteQuizRequest
	12, // 15: quiz.v1.QuestionService.CreateQuestionWithAnswers:input_type -> quiz.v1.CreateQuestionWithAnswersRequest
	15, // 16: quiz.v1.QuestionService.GetQuestion:input_type -> quiz.v1.GetQuestionRequest
	16, // 17: quiz.v1.QuestionService.GetAllQuestions:input_type -> quiz.v1.GetAllQuestionsRequest
	13, // 18: quiz.v1.QuestionService.UpdateQuestionWithAnswers:input_type -> quiz.v1.UpdateQuestionWithAnswersRequest
	17, // 19: quiz.v1.QuestionService.DeleteQuestion:input_type -> quiz.v1.DeleteQuestionRequest
	22, // 20: quiz.v1.QuizResultService.SubmitQuiz:input_type -> quiz.v1.SubmitQuizRequest
	25, // 21: quiz.v1.QuizResultService.GetQuizResults:input_type -> quiz.v1.GetQuizResultsRequest
	7,  // 22: quiz.v1.QuizService.CreateQuiz:output_type -> quiz.v1.QuizResponse
	7,  // 23: quiz.v1.QuizService.GetQuiz:output_type -> quiz.v1.QuizResponse
	8,  // 24: quiz.v1.QuizService.GetAllQuizzes:output_type -> quiz.v1.GetAllQuizzesResponse
	8,  // 25: quiz.v1.QuizService.GetMyQuizzes:output_type -> quiz.v1.GetAllQuizzesResponse
	10, // 26: quiz.v1.QuizService.PublishQuiz:output_type -> quiz.v1.PublishQuizResponse
	7,  // 27: quiz.v1.QuizService.UpdateQuiz:output_type -> quiz.v1.QuizResponse
	9,  // 28: quiz.v1.QuizService.DeleteQuiz:output_type -> quiz.v1.DeleteQuizResponse
	14, // 29: quiz.v1.QuestionService.CreateQuestionWithAnswers:output_type -> quiz.v1.QuestionWithAnswersResponse
	14, // 30: quiz.v1.QuestionService.GetQuestion:output_type -> quiz.v1.QuestionWithAnswersResponse
	18, // 31: quiz.v1.QuestionService.GetAllQuestions:output_type -> quiz.v1.GetAllQuestionsWithAnswersResponse
	14, // 32: quiz.v1.QuestionService.UpdateQuestionWithAnswers:output_type -> quiz.v1.QuestionWithAnswersResponse
	19, // 33: quiz.v1.QuestionService.DeleteQuestion:output_type -> quiz.v1.DeleteQuestionResponse
	24, // 34: quiz.v1.QuizResultService.SubmitQuiz:output_type -> quiz.v1.SubmitQuizResponse
	27, // 35: quiz.v1.QuizResultService.GetQuizResults:output_type -> quiz.v1.GetQuizResultsResponse
	22, // [22:36] is the sub-list for method output_type
	8,  // [8:22] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_quiz_v1_quiz_proto_init() }
func file_quiz_v1_quiz_proto_init() {
	if File_quiz_v1_quiz_proto != nil {
		return
	}
	file_quiz_v1_quiz_proto_msgTypes[3].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[4].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quiz_v1_quiz_proto_rawDesc), len(file_quiz_v1_quiz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_quiz_v1_quiz_proto_goTypes,
		DependencyIndexes: file_quiz_v1_quiz_proto_depIdxs,
		MessageInfos:      file_quiz_v1_quiz_proto_msgTypes,
	}.Build()
	File_quiz_v1_quiz_proto = out.File
	file_quiz_v1_quiz_proto_goTypes = nil
	file_quiz_v1_quiz_proto_depIdxs = nil
}
